/* Generated from @thefrontvintage Instagram posts (sold posts excluded). Newest first. */
window.THEFRONT_PRODUCTS = [
 {
  "id": "DdnfT_znwjw",
  "cat": "sofa",
  "name": "Cassina Maralunga 2.5 seater",
  "size": "가로 190cm 세로 85cm 높이 73cm 앉은 높이 45cm",
  "desc": "이탈리아 Cassina를 대표하는 아이코닉 소파 Maralunga입니다.\n이탈리아 건축가이자 디자이너인 Vico Magistretti가 1973년 디자인한 모델로, 부드럽고 볼륨감 있는 형태와 독특한 등받이 조절 기능이 특징입니다.\n\n등받이는 내부에 적용된 Cassina의 메커니즘을 통해 로우백과 하이백 형태로 자유롭게 전환할 수 있어 편안한 착석감을 제공합니다.\n\n이번에 입고된 마라룽가는 카키 베이스 컬러에 스트라이프 패턴이 적용된 패브릭 모델로, 2.5인용 사이즈 특유의 컴팩트한 비율을 갖추고 있습니다. 넓은 3인용 모델에 비해 공간에 부담 없이 배치할 수 있어 다양한 공간에 유연하게 활용하기 좋은 모델입니다.\n\n헤드레스트 정상적으로 작동하며 패브릭 상태는 좋은 컨디션 유지하고 있습니다.",
  "status": "new",
  "img": "images/products/DdnfT_znwjw.jpg",
  "ig": "https://www.instagram.com/p/DdnfT_znwjw/",
  "date": "September 22, 2026"
 },
 {
  "id": "DdiXcYJn55F",
  "cat": "table",
  "name": "Thonet Extendable Table set",
  "size": "테이블 가로 200cm - 280cm 세로 80cm  높이 75cm / 의자 가로 53cm 세로 52cm 84cm 앉은 높이 45cm",
  "desc": "독일 Thonet의 확장형 다이닝 테이블과 체어 세트입니다.\n내추럴 톤의 너도밤나무 무늬목을 사용해 따뜻한 우드 톤을 보여주며 견고하고 안정적인 구조로 제작되었습니다.\n\n테이블은 상판 내부에 수납된 2개의 확장판을 가운데로 펼쳐 결합하는 방식으로, 사용 인원과 공간에 따라 손쉽게 크기를 조절할 수 있습니다. 확장 시 약 280cm까지 길이가 늘어나 여러 명이 함께 사용하는 넉넉한 다이닝 공간으로 활용하기 좋습니다.\n\n총 7개의 체어가 함께 구성되어 있어 여유로운 인원으로 사용할 수 있으며, 테이블과 체어를 함께 배치해 통일감 있는 다이닝 공간을 연출할 수 있는 실용적인 세트입니다.",
  "status": "new",
  "img": "images/products/DdiXcYJn55F.jpg",
  "ig": "https://www.instagram.com/p/DdiXcYJn55F/",
  "date": "September 20, 2026"
 },
 {
  "id": "DdiVRr0nx1Y",
  "cat": "accessory",
  "name": "Cascando Coat Rack",
  "size": "높이 190cm",
  "desc": "네덜란드 디자인 브랜드 Cascando의 코트랙입니다. 네덜란드 디자이너 Peter van de Water가 디자인한 제품으로, 2008년경 Cascando 컬렉션에 소개되었습니다.\n\n별도의 벽면 고정이나 설치 없이 벽에 기대어 사용하는 제품으로 미니멀하고 기능적인 디자인이 돋보이는 제품입니다. 함께 구성된 전용 스테인리스 옷걸이가 포함되어 디자인의 완성도를 높여줍니다.\n\n불필요한 요소를 최소화한 간결한 구조와 독특한 사용 방식으로 2000년대 네덜란드 디자인의 특징을 잘 보여주는 제품입니다.",
  "status": "new",
  "img": "images/products/DdiVRr0nx1Y.jpg",
  "ig": "https://www.instagram.com/p/DdiVRr0nx1Y/",
  "date": "September 20, 2026"
 },
 {
  "id": "DdVn0_Bn-um",
  "cat": "chair",
  "name": "Westnofa Totem Chair",
  "size": "가로 54cm 세로 55cm 높이 88cm 앉은높이 46cm",
  "desc": "1980년대 노르웨이 가구 디자이너 Torstein Nilsen이 디자인하고 Westnofa에서 제작한 Totem 체어입니다.\n\n부채꼴 형태로 펼쳐지는 독특한 등받이가 특징으로 스칸디나비안 디자인을 기반으로 한 1980년대 포스트모던 특유의 조형미를 보여주는 제품입니다. 너도밤나무 베이스에 브라운 패브릭 좌판의 조화로 팔걸이가 없는 버전으로 입고되었습니다.\n\n다이닝 체어는 물론 공간에 포인트를 주는 독립적인 체어로도 활용하기 좋은 디자인입니다.",
  "status": "new",
  "img": "images/products/DdVn0_Bn-um.jpg",
  "ig": "https://www.instagram.com/p/DdVn0_Bn-um/",
  "date": "September 15, 2026"
 },
 {
  "id": "DdVlcJlH9IN",
  "cat": "sofa",
  "name": "Cassina Maralunga 2 seater",
  "size": "가로 165cm 세로 80cm 높이 73cm",
  "desc": "1973년 이탈리아 디자이너 비코 마지스트레티가 디자인하고, Cassina 에서 제작한 Maralunga 소파입니다.\n\n부드럽게 감싸는 듯한 편안한 착석감과 등받이 상단을 접었다 펼칠 수 있는 독특한 헤드레스트 구조가 특징인 디자인으로, 1970년대 이탈리아 모던 디자인을 대표하는 제품 중 하나입니다.\n\n해당 마라룽가는 오리지널 블랙 가죽으로 입고되었으며, 가죽 상태와 헤드레스트 메커니즘 모두 전반적으로 좋은 컨디션을 유지하고 있습니다.",
  "status": "new",
  "img": "images/products/DdVlcJlH9IN.jpg",
  "ig": "https://www.instagram.com/p/DdVlcJlH9IN/",
  "date": "September 15, 2026"
 },
 {
  "id": "DdTfG9Pn6gf",
  "cat": "table",
  "name": "Ligne Roset Extensia Table",
  "size": "가로 160cm (확장시 280cm) 세로 94cm 높이 75cm",
  "desc": "프랑스 가구 브랜드 Ligne Roset에서 제작한 Extensia 확장형 빈티지 다이닝 테이블입니다.\n\n유리 상판 두장이 서로 겹쳐진 상태에서 좌우로 슬라이딩되며 확장되는 구조가 특징입니다.\n\n평소에는 6인용으로 사용하고 확장 시 10인까지 넉넉하게 사용할 수 있어 실용성과 공간 활용도가 뛰어난 제품입니다.\n\n프로스트 글라스 특유의 은은한 반투명감과 너도밤나무 프레임의 따뜻한 질감, 정사각형 패턴이 어우러져 그 당시 유럽 모던 디자인 특유의 분위기를 잘 보여주는 빈티지 테이블입니다.",
  "status": "new",
  "img": "images/products/DdTfG9Pn6gf.jpg",
  "ig": "https://www.instagram.com/p/DdTfG9Pn6gf/",
  "date": "September 15, 2026"
 },
 {
  "id": "DdBj-mJH_ZU",
  "cat": "chair",
  "name": "Acerbis Serenissima Chair",
  "size": "가로 46cm 세로 50 cm 높이 121cm 앉은 높이 45cm",
  "desc": "1980년대 이탈리아 Acerbis의 Serenissima 다이닝 체어입니다.\n\n이탈리아 디자이너 Lella &amp; Massimo Vignelli가 디자인한 모델로 일반적인 체어와 달리 등받이가 후면 프레임과 뒷다리까지 이어지는 독창적인 구조가 특징입니다.\n\n블랙 레더 시트와 메탈 소재로 제작되었으며 반복되는 사각 패턴을 적용해 시각적 인상을 보여줍니다.\n\n자연스러운 사용감 외 전체적으로 좋은 컨디션 유지하고 있습니다.",
  "status": "new",
  "img": "images/products/DdBj-mJH_ZU.jpg",
  "ig": "https://www.instagram.com/p/DdBj-mJH_ZU/",
  "date": "September 8, 2026"
 },
 {
  "id": "Dc--Ch0n3Dr",
  "cat": "sofa",
  "name": "Cassina Maralunga 3 seater",
  "size": "가로 236cm 세로 90cm 높이 72 cm  앉은높이 42 cm",
  "desc": "1973년 비코 마지스테티가 이탈리아 Cassina를 위해 디자인한 마라룽가 모델입니다.\n\n오리지널 패브릭으로 스트라이프 패턴이 있는 3인 사이즈 소파입니다. 전체적으로 좋은 컨디션으로 입고되었으며 등받이 부분도 정상으로 작동합니다.\n\n까시나 모노그램과 오리지널 라벨 있습니다.",
  "status": "new",
  "img": "images/products/Dc--Ch0n3Dr.jpg",
  "ig": "https://www.instagram.com/p/Dc--Ch0n3Dr/",
  "date": "September 7, 2026"
 },
 {
  "id": "Dc-ZVden3Lg",
  "cat": "chair",
  "name": "Harvink Zino Chair",
  "size": "가로 43cm 세로 44cm 높이 92cm | 좌석 높이 47cm",
  "desc": "1980년대 네덜란드 Harvink에서 제작한 Zino 모델입니다.\n\n우드 등받이와 메탈 프레임 베이스, 검정 가죽 좌판으로 구성되어 있으며, 견고한 구조와 안정적인 착석감을 갖춘 의자입니다.\n\n간결한 디자인과 소재의 조화가 돋보이는 제품으로, 네덜란드 가구 특유의 분위기를 잘 보여줍니다.",
  "status": "new",
  "img": "images/products/Dc-ZVden3Lg.jpg",
  "ig": "https://www.instagram.com/p/Dc-ZVden3Lg/",
  "date": "September 6, 2026"
 },
 {
  "id": "DcAqV0KkX6D",
  "cat": "table",
  "name": "Hulmefa Coffee Table",
  "size": "가로 150cm 확장시 242cm 세로 50cm 높이 43cm",
  "desc": "1960년대 네덜란드 Hulmefa의 확장형 커피 테이블입니다.\n티크 우드 베이스와 슬림한 테이퍼드 다리가 조화를 이루는 디자인으로 양쪽으로 펼쳐지는 슬라이딩 확장 구조가 특징입니다.\n\n자연스러운 생활 사용감 및 스크래치 존재합니다.",
  "status": "available",
  "img": "images/products/DcAqV0KkX6D.jpg",
  "ig": "https://www.instagram.com/p/DcAqV0KkX6D/",
  "date": "August 13, 2026"
 },
 {
  "id": "DbxZUR5kQT4",
  "cat": "chair",
  "name": "Skandi Form Armchair",
  "size": "가로 68cm 세로 58cm 높이 120cm | 앉은 높이 45cm",
  "desc": "스웨덴 Skandiform의 1980년대 빈티지 암체어입니다.\n높은 하이백 디자인에 깊이감 있는 블루 패브릭, 원목 프레임과 팔걸이가 조화를 이루는 스칸디나비안 디자인의 라운지 체어입니다.\n\n특히 등받이와 좌판 각도 조절이 가능한 리클라이닝 구조를 갖추고 있어 사용자의 자세에 맞춰 편안하게 세팅할 수 있습니다.\n\n1980년대 북유럽 빈티지 가구 특유의 분위기를 잘 보여주는 일인 암체어로 거실이나 서재 등 다양한 공간에서 활용하기 좋은 아이템입니다.",
  "status": "available",
  "img": "images/products/DbxZUR5kQT4.jpg",
  "ig": "https://www.instagram.com/p/DbxZUR5kQT4/",
  "date": "August 8, 2026"
 },
 {
  "id": "DbneGIBn89T",
  "cat": "sofa",
  "name": "Artifort C683 3 Seater Sofa",
  "size": "가로 183 세로 87cm 높이 79cm 앉은 높이 43cm",
  "desc": "네덜란드 Artifort의 대표적인 모델인 C683 3인용 소파입니다.\n\n인도네시아 출신 네덜란드 디자이너 Kho Liang Ie가 1968년에 디자인한 모델로 이후 오랜 기간 Artifort 컬렉션으로 생산되며 브랜드를 대표하는 아이코닉한 디자인으로 자리 잡았습니다.\n\n해당 모델은 3인 사이즈로 여유로운 착석 공간과 편안함을 제공합니다. 하나로 이어진 등받이와 좌방석, 쿠션 라인이 특징이며 슬림한 베이스와 조화를 이루어 가볍고 미니멀한 인상을 보여줍니다.\n\nKho Liang Ie는 불필요한 장식을 배제하고 공간과 가구의 관계를 중요하게 생각했던 디자이너로 C683 모델에서도 그의 철학이 잘나타납니다.",
  "status": "available",
  "img": "images/products/DbneGIBn89T.jpg",
  "ig": "https://www.instagram.com/p/DbneGIBn89T/",
  "date": "August 4, 2026"
 },
 {
  "id": "Dbk1v0NH3dg",
  "cat": "chair",
  "name": "Tecta D20 Chair",
  "size": "가로 53cm | 세로 59cm | 높이 92cm | 좌면 높이 47cm",
  "desc": "독일 Tecta의 D20 모델입니다.\n\n바우하우스 디자인 철학을 계승하는 Tecta의 대표적인 체어 컬렉션 중 하나로 슬림한 스틸 프레임과 블랙 라탄 소재가 조화를 이루는 디자인입니다.\n\n전체적으로 좋은 컨디션을 유지하고 있으며 오리지널 Tecta 라벨 스티커가 보존되어 있습니다.",
  "status": "available",
  "img": "images/products/Dbk1v0NH3dg.jpg",
  "ig": "https://www.instagram.com/p/Dbk1v0NH3dg/",
  "date": "August 3, 2026"
 },
 {
  "id": "DbZ-hSoERdB",
  "cat": "chair",
  "name": "Alice Cattelan Dinning Chair",
  "size": "가로 45cm 세로 44 cm 높이 108cm | 앉은 높이 48cm",
  "desc": "Giorgio Cattelan이 디자인한 Cattelan Italia의 Alice 하이백 다이닝 체어입니다.\n\n1980년대 제작된 초기 모델로, 긴 등받이의 직선적인 형태가 돋보이며 깊이 있는 청록 색상의 통가죽 마감이 매력적인 제품입니다.\n\n전체적으로 좋은 컨디션 유지하고 있습니다.",
  "status": "available",
  "img": "images/products/DbZ-hSoERdB.jpg",
  "ig": "https://www.instagram.com/p/DbZ-hSoERdB/",
  "date": "July 29, 2026"
 },
 {
  "id": "DbVVDyqHzW1",
  "cat": "chair",
  "name": "Thonet s320 Armchair",
  "size": "사이즈 문의",
  "desc": "",
  "status": "available",
  "img": "images/products/DbVVDyqHzW1.jpg",
  "ig": "https://www.instagram.com/p/DbVVDyqHzW1/",
  "date": "July 28, 2026"
 },
 {
  "id": "DbU67apEdzr",
  "cat": "accessory",
  "name": "Brendel Leuchten Floor Lamp",
  "size": "높이 196cm 지름 26cm",
  "desc": "1970년대 독일 Brendel Leuchten에서 제작한 빈티지 플로어 램프입니다.\n독일 모더니즘 디자인 특유의 절제된 미니멀리즘과 뛰어난 기능성이 조화를 이루는 램프로 슬림한 크롬 프레임과 간결한 메탈 헤드로 구성되어있습니다.\n\nBrendel Leuchten는 베를린을 기반으로 활동한 독일 조명 제조사로, 1970~80년대 산업디자인과 바우하우스의 영향을 받은 기능주의 조명을 선보였습니다.\n\n크롬 지지대는 3단 분리 가능하며 헤드의 높낮이도 쉽게 조절 가능하여 다양한 빛의 각도 연출 가능합니다.\n\n세월에 따른 자연스러운 사용감은 있으나 전체적으로 우수한 빈티지 컨디션을 유지하고 있습니다.",
  "status": "available",
  "img": "images/products/DbU67apEdzr.jpg",
  "ig": "https://www.instagram.com/p/DbU67apEdzr/",
  "date": "July 27, 2026"
 },
 {
  "id": "DZzVtWykTim",
  "cat": "sofa",
  "name": "Saporiti Wave Sofa",
  "size": "가로 165cm 세로 98cm 높이 72cm | 앉은 높이 42cm",
  "desc": "1974년 이탈리아 디자이너 Giovanni Offredi가 Saporiti Italia를 위해 디자인한 Wave 소파입니다.\n\n노출된 스틸 프레임 구조와 파도처럼 흐르는 유기적인 일체형 좌판 및 등받이가 특징이며 당시 항공기와 자동차 산업에서 영감을 받은 기술과 산업적 미학을 가구 디자인에 접목한 대표작입니다.\n\n특히 공중에 떠 있는 듯한 구조감과 유려한 실루엣은 1970~80년대 이탈리아 모더니즘과 포스트모던 디자인 흐름을 반영하며 출시 이후 현재까지도 Saporiti 컬렉션을 대표하는 클래식 모델로 평가받고 있습니다.\n\n민트 계열의 스웨이드 소재의 패브릭으로 시각적 존재감이 있는 소파입니다.\n\n하단 프레임에 오리지널 브랜드 라벨이 보존되어 있으며 자연스러운 사용감 존재합니다.",
  "status": "available",
  "img": "images/products/DZzVtWykTim.jpg",
  "ig": "https://www.instagram.com/p/DZzVtWykTim/",
  "date": "June 20, 2026"
 },
 {
  "id": "DZpDPOvn-cK",
  "cat": "chair",
  "name": "Kimball International Bingo Chair",
  "size": "의자 가로 50 cm 세로 47cm 높이 83cm | 앉은 높이 45cm / 테이블 가로 200cm 세로 80cm 높이 75cm",
  "desc": "미국 가구 브랜드 Kimball International의 Bingo 스태킹 체어입니다.\n\n1990년대부터 사무실, 카페, 주거 공간 등 다양한 환경에서 널리 사용된 모델로, 북유럽 디자인의 간결함과 미드센추리 모던의 실용성이 잘 드러나는 제품입니다.\n\n좌판과 등받이는 성형 합판으로 제작되었으며, 하부는 크롬 도금된 금속 프레임으로 구성되어 뛰어난 내구성과 안정성을 제공합니다.\n\n또한 일체형 팔걸이 구조로 편안한 착석감을 더했으며, 위로 쌓아 보관할 수 있도록 설계되어 공간 활용에 매우 편리한 의자입니다.\n\n본 의자와 함께 사용할 수 있는 테이블도 세트로 판매 중입니다.",
  "status": "available",
  "img": "images/products/DZpDPOvn-cK.jpg",
  "ig": "https://www.instagram.com/p/DZpDPOvn-cK/",
  "date": "June 16, 2026"
 },
 {
  "id": "DZXWuHWH4SV",
  "cat": "table",
  "name": "Pastoe TM6110 Table &amp; SM0301 Chair",
  "size": "TM6110 가로 173cm 세로 96cm 높이 73cm / SM0301 가로 50cm 세로 41cm 높이 76cm | 앉은 높이 45cm",
  "desc": "1972년 네덜란드 디자이너 Pierre Mazairac가 Pastoe를 위해 디자인한 TM6110 테이블과 SM0301 체어 세트입니다.\n\n당시 네덜란드 모더니즘을 대표하는 디자인으로, 노출된 결합부와 간결한 직선 구조를 통해 1970년대 산업 디자인의 특징을 잘 보여줍니다.\n\n테이블 상판은 내구성이 뛰어난 블랙 포미카(Formica)로 마감 되었으며, 의자와 테이블 프레임은 아노다이징 처리된 알루미늄으로 제작되어 가볍고 견고한 구조를 갖추고 있습니다.\n\n현재는 생산이 단종된 모델로 TM6110 테이블 1점과 SM0301 체어 6점으로 구성된 세트는 비교적 희소성이 높은 편입니다.\n\n생활 스크래치 및 사용감 외 전체적으로 좋은 컨디션으로 입고되었습니다.",
  "status": "available",
  "img": "images/products/DZXWuHWH4SV.jpg",
  "ig": "https://www.instagram.com/p/DZXWuHWH4SV/",
  "date": "June 9, 2026"
 },
 {
  "id": "DX6LrN2ketY",
  "cat": "chair",
  "name": "Fasem S44 Chair",
  "size": "가로 45 cm 깊이 55cm 높이 104cm | 앉은 높이 46cm",
  "desc": "1980년대에 Giancarlo Vegni와 Gianfranco Gualtierotti가 디자인하고, 이탈리아 브랜드 Fasem에서 제작한 S44 모델입니다.\n\n얇은 금속 구조와 높은 등받이를 특징으로 공간을 많이 차지하지 않으면서도 존재감이 돋보이는 디자인입니다.\n\n좌석과 등받이는 천연 가죽으로 마감되어 있으며 자연스러운 사용감 외 전반적으로 좋은 상태 유지하고 있습니다.",
  "status": "available",
  "img": "images/products/DX6LrN2ketY.jpg",
  "ig": "https://www.instagram.com/p/DX6LrN2ketY/",
  "date": "May 4, 2026"
 },
 {
  "id": "DXvmkdmkcfd",
  "cat": "chair",
  "name": "Alias Spaghetti Chair",
  "size": "가로 40cm 세로 51cm 높이 84cm | 좌석 높이46 cm",
  "desc": "1980년대 Giandomenico Belotti가 Alias를 위해 디자인한 스파게티 체어입니다.\n\n이탈리아 모던 디자인을 대표하는 아이코닉 피스로 간결한 스틸 프레임 위에 PVC 소재를 활용하여 스트랩 형태의 좌판을 만들었으며 기능성과 조형미를 동시에 구현했습니다.\n\n가볍고 유연한 구조의 편안한 착석감은 물론, 미니멀한 실루엣으로 다양한 공간에서 사용 가능합니다.\n\n입고된 모델은 후기 생산된 모델로 전체적으로 훌륭한 컨디션 유지하고 있습니다.",
  "status": "available",
  "img": "images/products/DXvmkdmkcfd.jpg",
  "ig": "https://www.instagram.com/p/DXvmkdmkcfd/",
  "date": "April 29, 2026"
 },
 {
  "id": "DXYa-08kTV1",
  "cat": "sofa",
  "name": "Cassina Maralunga 2 seater sofa",
  "size": "가로 165cm 깊이 80cm 높이 70cm 착석높이 45cm",
  "desc": "1973년 비코마지스트레티가 이탈리아 까시나를 위해 디자인한 마라룽가 2인 소파입니다.\n\n까시나를 대표하는 아이코닉 모델로, 등받이와 헤드레스트 각도 조절이 가능하며 편안한 착석감을 제공합니다.\n\n강렬한 레드 스웨이드 컬러로 공간에 포인트를 주기 좋은 제품이며 생활 사용감 외 전체적으로 좋은 컨디션 유지하고 있습니다.\n\n헤드레스트 부분 정상적으로 작동되며 까시나 오리지널 라벨과 모노그램 있는 버젼입니다.",
  "status": "available",
  "img": "images/products/DXYa-08kTV1.jpg",
  "ig": "https://www.instagram.com/p/DXYa-08kTV1/",
  "date": "April 20, 2026"
 },
 {
  "id": "DXECPdMEQO8",
  "cat": "table",
  "name": "Castelijn Strip Chair &amp; Round Table",
  "size": "가로 44cm 깊이 53cm 높이 77cm | 앉은 높이 45cm / 지름 120cm 높이 72.5cm",
  "desc": "1970년대 네덜란드 산업 디자이너 Gijs Bakker가 Castelijn을 위해 디자인한 Strip 체어입니다.\n\n당시 유럽에서 드물었던 벤트우드 기술을 적용하여 얇은 나무 판재를 여러 겹 쌓아 곡선으로 만든 구조로 못이나 금속 구조 없이 목재 자체의 텐션으로 완성한 모델입니다.\n\n불필요한 장식을 배제하고 등받이, 좌판, 다리가 하나의 흐름처럼 이어지는 형태로 미니멀하면서 볼륨감이 살아있는 조형미가 돋보이는 의자입니다.\n\nCastelijn에서 제작된 라운드 테이블과 함께 매칭된 구성입니다.\n\n테이블과 의자 모두 오리지널 라벨 스티커가 보존되어 있으며\n생활사용감 외에 전체적으로 좋은 컨디션입니다.",
  "status": "available",
  "img": "images/products/DXECPdMEQO8.jpg",
  "ig": "https://www.instagram.com/p/DXECPdMEQO8/",
  "date": "April 13, 2026"
 },
 {
  "id": "DWyQqmAEf9V",
  "cat": "chair",
  "name": "Westnofa Siesta Chair",
  "size": "가로 65cm 세로 60cm 높이 85cm | 앉은 높이 45cm",
  "desc": "노르웨이 디자이너 Ingmar Relling이 1965년에 디자인하고\nWestnofa에서 생산된 Siesta 체어입니다.\n스칸디나비안 모던 디자인을 대표하는 아이코닉한 라운지 체어로 편안한 착석감은 물론, 가볍지만 견고한 구조로 제작된 너도밤나무의 벤트 우드 프레임과 짙은 고동색 컬러의 가죽 쿠션 조화로 구성되어 있습니다.\n\nWestnofa는 디자이너들과의 협업을 통해 대량 생산과 글로벌 수출에 성공한 브랜드로, 특히 Siesta 모델은 60~70년대 미국 시장에서 큰 호응을 얻으며 노르웨이 가구 디자인을 세계에 알린 대표적인 체어입니다.\n\n자연스러운 사용감 외 전체적으로 좋은 컨디션 유지하고 있으며 오리지널 라벨도 보존되어 있습니다.",
  "status": "available",
  "img": "images/products/DWyQqmAEf9V.jpg",
  "ig": "https://www.instagram.com/p/DWyQqmAEf9V/",
  "date": "April 6, 2026"
 },
 {
  "id": "DWX79wAEZYv",
  "cat": "table",
  "name": "Läsko Studioform International Folding Table",
  "size": "가로 92cm  세로 92cm 높이 72cm / 확장시 가로 130cm 세로 130cm 높이 72cm",
  "desc": "1970년대 독일 가구 회사 Läsko Studioform International에서 제작한 폴딩 테이블입니다.\n\n하부의 금속 베이스와 화이트 라미네이트 상판 구성으로 사각 형태에서 하단에 있는 레버를 당겨 원형으로 변경 가능합니다.\n각 레버는 개별적으로 작용하여 공간 상황에 맞게 원하는 부위만 펼처 사용 가능합니다.\n\n70년대에는 모듈형, 변형 가능한 생활가구들이 많이 제작되었으며 거주 공간에서 실용적으로 사용할 수 있는 디자인들이 탄생했습니다.\n\n이 테이블 역시 당시의 시대적 흐름을 잘 보여주는 제품으로,\n기능적인 구조와 미래적인 조형미를 동시에 갖춘 1970년대 유럽 모던 디자인 가구입니다.",
  "status": "available",
  "img": "images/products/DWX79wAEZYv.jpg",
  "ig": "https://www.instagram.com/p/DWX79wAEZYv/",
  "date": "March 26, 2026"
 },
 {
  "id": "DWLQlDFEeaH",
  "cat": "sofa",
  "name": "Italian Amanta Lounge Sofa by Mario Bellini for C&amp;b",
  "size": "가로 80cm 세로 76cm 높이 70cm | 좌석높이 45cm",
  "desc": "",
  "status": "available",
  "img": "images/products/DWLQlDFEeaH.jpg",
  "ig": "https://www.instagram.com/p/DWLQlDFEeaH/",
  "date": "March 21, 2026"
 },
 {
  "id": "DV_WPhrEYpK",
  "cat": "chair",
  "name": "Thonet s3001 Armchair",
  "size": "가로 76cm 세로 70cm 높이 76cm 앉은 높이 43cm",
  "desc": "1990년대 Christoph Zschocke가 Thonet을 위해 디자인한 S3001 암체어입니다.\n\n자작나무로 제작된 곡선형 등받이와 묵직한 바디를 안정적으로 지지하는 크롬 스틸 튜브 하부 프레임으로 구성되어 있으며, 로얄 블루 컬러의 오리지널 가죽으로 마감되었습니다.\n\n직선과 곡선이 조화를 이루며 기능주의적 디자인이 잘 드러나는 미니멀한 디자인의 소파입니다.\n낮고 넓은 좌석과 몸을 감싸는 형태로 설계되어 라운지나 대기 공간 등 편안하게 사용하기에 적합합니다.\n\n자연스러운 사용감 외에 전제척으로 좋은 컨디션으로 입고되었습니다.",
  "status": "available",
  "img": "images/products/DV_WPhrEYpK.jpg",
  "ig": "https://www.instagram.com/p/DV_WPhrEYpK/",
  "date": "March 17, 2026"
 },
 {
  "id": "DVs1zbnER59",
  "cat": "sofa",
  "name": "Cassina Maralunga 2 seater",
  "size": "가로 165cm 세로 80cm 높이 70cm | 착석 높이 45cm",
  "desc": "1973년에 비코 마지스트레티가 까시나를 위해 디자인한 마라룽가 2인 소파입니다.\n\n검정색 이태리 소가죽으로 새롭게 가죽 교체되어 입고 되었으며 등받이 헤드레스트 부분 정상적으로 작동됩니다.\n\n쿠션 아래 까시나 모노그램과 오리지널 라벨 있는 모델입니다.",
  "status": "available",
  "img": "images/products/DVs1zbnER59.jpg",
  "ig": "https://www.instagram.com/p/DVs1zbnER59/",
  "date": "March 10, 2026"
 },
 {
  "id": "DVYPeZFkSDH",
  "cat": "chair",
  "name": "Pietro Costantini Dinning Armchair",
  "size": "가로 44cm 세로 45cm 높이 96cmᅵ앉은 높이 47cm",
  "desc": "1980년대 이탈리아의 고급 가구 브랜드 피에트로 콘스탄티니에서 제작한 다이닝 암체어입니다.\n\n세련된 모던 스타일을 바탕으로, 긴 등받이와 곡선형 팔걸이가 강조된 디자인이 특징으로, 얇으면서도 견고하게 설계된 다리 구조와 인체공학적으로 디자인된 등받이 라인은 기능성과 형태미의 균형을 중시한 당시의 디자인 철학을 잘 보여줍니다.\n\n의자 전체는 고급 가죽으로 마감되었으며, 오랜 시간이 흐르면서 자연스럽게 형성된 에이징이 분위기를 더해줍니다. 자연스러운 생활 흔적 외에는 전반적으로 좋은 컨디션으로 입고되었습니다.",
  "status": "available",
  "img": "images/products/DVYPeZFkSDH.jpg",
  "ig": "https://www.instagram.com/p/DVYPeZFkSDH/",
  "date": "March 2, 2026"
 },
 {
  "id": "DUaITl5EfAn",
  "cat": "chair",
  "name": "Penelope Chair",
  "size": "가로 56cm · 세로 54cm · 높이 78cm | 앉은 높이 45cm",
  "desc": "1982년 찰스 폴록이 디자인하고, 이탈리아 가구 회사 안토니오 카스텔리에서 제작한 페넬로페 체어입니다.\n\n촘촘한 그물망을 연상시키는 일체형 좌판과 등받이는 메탈 메쉬 소재로 제작되었으며, 삼각 형태의 다리 구조로 인해 마치 공중에 떠 있는 듯한 시각적 인상을 줍니다.\n\n인체공학적으로 설계된 시트 쉘은 사용자의 몸을 자연스럽게 감싸주고, 일체형 팔걸이에는 플라스틱 패드가 적용되어 착석감을 한층 더했습니다. 특히 등받이의 유려한 곡선은 디자인적 요소뿐 아니라 여러 개를 쌓아 올릴 수 있도록 설계되어, 스태킹 시 손잡이 역할을 하는 실용적인 기능까지 담아내고 있습니다.\n\n페넬로페 체어는 조형적으로 완성도 높은 디자인은 물론, 기능성 또한 뛰어난 의자로 회의실, 대기 공간, 주거 공간 등 다양한 환경에서 활용이 가능합니다.",
  "status": "available",
  "img": "images/products/DUaITl5EfAn.jpg",
  "ig": "https://www.instagram.com/p/DUaITl5EfAn/",
  "date": "February 5, 2026"
 },
 {
  "id": "DTh0lbpkSmR",
  "cat": "table",
  "name": "USM Kitos Desk",
  "size": "가로 180cm 세로 90cm 높이 75cm",
  "desc": "스위스 가구 브랜드 USM에서 제작한 Kitos 데스크입니다.\n\n세련되고 미니멀한 디자인의 테이블로, 크롬 스틸 프레임과 흰색 라미네이트 상판으로 제작되었습니다.\n\n모듈형 시스템을 자랑하는 USM 가구인 만큼, 해당 모델 역시 상판 넓이 확장 및 프레임 확장이 가능합니다.\n\n테이블 상판은 180cm의 넉넉한 넓이로 사무실·집·회의 공간 등 다양한 용도로 사용 가능하며, 어떤 공간에도 자연스럽게 어우러집니다.\n\n해당 모델은 높이 조절 기능이 없는 고정형 테이블입니다.",
  "status": "available",
  "img": "images/products/DTh0lbpkSmR.jpg",
  "ig": "https://www.instagram.com/p/DTh0lbpkSmR/",
  "date": "January 15, 2026"
 },
 {
  "id": "DTKx2qfkZT0",
  "cat": "sofa",
  "name": "Cassina Maralunga 2 seater sofa",
  "size": "가로 165cm 깊이 80cm 높이 70cm | 착석높이 45cm",
  "desc": "1973년 비코 마지스트레티가 이태리 까시나를 위해 디자인한 마라룽가 2인 모델입니다.\n브라운 컬러이며, 등받이와 헤드레스트 각도를 조절할 수 있는 구조가 특징입니다.\n\n사용자의 자세에 따라 편안함을 극대화하도록 설계된 디자인으로, 출시 이후 까시나를 대표하는 아이코닉 소파로 자리 잡았습니다.\n\n해당 제품은 까시나 오리지널 라벨과 모노그램이 모두 있는 모델입니다.",
  "status": "available",
  "img": "images/products/DTKx2qfkZT0.jpg",
  "ig": "https://www.instagram.com/p/DTKx2qfkZT0/",
  "date": "January 6, 2026"
 },
 {
  "id": "DTKxbxvEaMU",
  "cat": "table",
  "name": "Metaform M1 Coffee Table",
  "size": "가로 60cm 세로 65.5cm 높이 36cm / 가로 90cm 세로 95cm 높이 36cm / 가로 100cm 세로 105.5cm 높이 36cm",
  "desc": "1980년대 네덜란드 디자이너 Hank Kwint가Metaform을 위해 디자인한 커피 테이블입니다.\n\n크롬 스틸 프레임과 두꺼운 유리 상판으로 구성된 미니멀하고 모던한 구조가 돋보이며, 1980년대 네덜란드 모던 디자인의 감성을 잘 보여줍니다.\n\n출시 당시 M1 시리즈는 여러 쉐입과 사이즈로 제작되었고, 과하지 않은 세련된 디자인으로 다양한 공간에 잘 어우러지는 테이블입니다.\n\n세가지 사이즈의 직사각형 테이블로 입고되었습니다.",
  "status": "available",
  "img": "images/products/DTKxbxvEaMU.jpg",
  "ig": "https://www.instagram.com/p/DTKxbxvEaMU/",
  "date": "January 6, 2026"
 },
 {
  "id": "DSZg-iPkbWH",
  "cat": "chair",
  "name": "Black Dutch Wood Chair",
  "size": "가로 43cm 깊이 49cm 높이 81cm 앉은 높이 46cm",
  "desc": "우드 소재로 제작된 네덜란드 빈티지 스태킹 체어가 재입고 되었습니다.\n스칸디나비안 디자인 특유의 간결하고 따뜻한 미감이 돋보이며, 넉넉한 좌판과 등받이 뒤편에 마련된 작은 트레이는 책이나 소품을 올려둘 수 있어 실용성을 더합니다.\n\n여러 개를 위로 쌓아 보관할 수 있어 공간 활용에 효율적이며, 가정은 물론 카페나 스튜디오 등 다양한 공간에서 편안하게 활용할 수 있는 체어입니다.",
  "status": "available",
  "img": "images/products/DSZg-iPkbWH.jpg",
  "ig": "https://www.instagram.com/p/DSZg-iPkbWH/",
  "date": "December 18, 2025"
 },
 {
  "id": "DSUaLP2EW1K",
  "cat": "chair",
  "name": "Ligne Roset Zen Chair",
  "size": "가로 77 깊이 78 높이 105cm 앉은 높이 38 cm",
  "desc": "1980년대 프랑스 디자이너 Claude Brisson이 Ligne Roset를 위해 디자인한 Zen 라운지 체어입니다.\n\n토고(Togo)와 쁠룸(Ploum) 소파로 잘 알려진 리네로제는 프랑스를 대표하는 하이엔드 모던 가구 브랜드로, Zen 역시 뛰어난 완성도를 보여주는 모델입니다.\n\n넉넉한 좌판과 편안한 착석감을 중심으로 설계된 1인용 라운지 체어로, 오토만과 함께 구성된 제품이며 1980년대 특유의 포스트모던 감성이 조형적으로 잘 드러납니다.\n\n입고된 제품은 Kvadrat 패브릭으로 리업홀스터리되어 분홍색과 연두색의 투톤패턴이 조화롭게 어우러지며, 공간에 강렬한 시각적 포인트를 더해줍니다.\n\n현재는 단종되어 더 이상 생산되지 않는 모델로, 빈티지 라인에서만 만나볼 수 있는 희소한 제품입니다.",
  "status": "available",
  "img": "images/products/DSUaLP2EW1K.jpg",
  "ig": "https://www.instagram.com/p/DSUaLP2EW1K/",
  "date": "December 16, 2025"
 },
 {
  "id": "DR1QhC3kVsY",
  "cat": "table",
  "name": "Trivette Table TM06",
  "size": "가로 140cm 세로 140cm 높이 73cm",
  "desc": "1990년대 네덜란드 디자이너 Frans Schrofer가 Hennie de Jong을 위해 디자인한 Trivette 시리즈(TM05–TM09) 중 TM06 모델입니다.\n\nTM06 테이블은 육각형 체리 우드 상판과 블랙 에폭시 마감의 스틸 프레임이 조화를 이루는 구조로, 1992년 Dutch Design Award에서 우수상을 수상한 작품입니다.\n\n넓은 면적의 상판은 다양한 용도로 활용될 수 있어, 디자이너가 추구한 실용성과 미감의 균형을 자연스럽게 드러냅니다.\n\nSchrofer는 “삶을 위한 도구 만들기”라는 철학 아래 기능성과 아름다움을 겸비한 현대 가구를 선보였으며, BoConcept을 비롯한 여러 국제 가구 브랜드와 협업한 바 있습니다.",
  "status": "available",
  "img": "images/products/DR1QhC3kVsY.jpg",
  "ig": "https://www.instagram.com/p/DR1QhC3kVsY/",
  "date": "December 3, 2025"
 },
 {
  "id": "DRb0odSkRgI",
  "cat": "chair",
  "name": "Thonet s320 Chair",
  "size": "가로 55cm 세로 58cm 높이 78 cm | 앉은 높이 45cm",
  "desc": "독일 브랜드 THONET(토넷)의 s320 암체어입니다.\n\n가볍고 내구성 높은 스틸 구조에 성형 목재 좌판을 더해 제작되었으며 스태킹이 가능하여 다양한 공간에서 활용하기 좋은 실용적인 디자인입니다.\n\n팔걸이 부분은 자연스러운 사용감 존재하며 검정 패브릭 컬러로 새롭게 천갈이되어 입고되었습니다.",
  "status": "available",
  "img": "images/products/DRb0odSkRgI.jpg",
  "ig": "https://www.instagram.com/p/DRb0odSkRgI/",
  "date": "November 24, 2025"
 },
 {
  "id": "DRRjNNfkf__",
  "cat": "sofa",
  "name": "Cassina Maralunga 2 Seater Sofa",
  "size": "가로 160cm 깊이 85cm 높이 70cm 앉은 높이 42cm",
  "desc": "1973년, 비코 마지스트레티가 이탈리아의 까시나를 위해 디자인한 마라룽가소파입니다.\n까시나 특허인 자전거 체인 메커니즘을 적용해 등받이 각도를 조절할 수 있도록 설계된 이 소파는, 단순한 편안함을 넘어 구조적 혁신을 통해 사용자 경험을 새롭게 정의한 산업 디자인의 아이콘입니다.\n\n외관은 온화하고 부드러운 인상을 주면서도, 내부 구조는 정교하고 기능적으로 설계되어 디자인과 실용성의 완벽한 균형을 보여주는 대표적인 사례로 평가받으며, 오늘날까지 꾸준히 사랑받고 있는 모델입니다.\n\n해당 모델은 네이비와 레드 스트라이프 패턴이 어우러져 보랏빛 컬러감을 띠며, 까시나 모노그램과 오리지널 라벨까지 모두 갖춘 좋은 컨디션으로 입고되었습니다.",
  "status": "available",
  "img": "images/products/DRRjNNfkf__.jpg",
  "ig": "https://www.instagram.com/p/DRRjNNfkf__/",
  "date": "November 20, 2025"
 },
 {
  "id": "DRO3Fhgkdko",
  "cat": "cabinet",
  "name": "Brutalist Wood Cabinet",
  "size": "가로 117cm 폭 42cm 높이 134 cm",
  "desc": "1970년대 벨기에에서 제작된 브루탈리스트 수납장입니다.\n\n당시 벨기에의 여러 공방과 소규모 캐비닛 제작 업체들은 시대적 흐름에 따라 브루탈리즘 스타일의 캐비닛과 사이드보드를 제작했으며, 이 과정에서 다양한 그래픽 패턴의 도어 디자인이 탄생했습니다.\n\n이 수납장은 서로 다른 방향으로 뻗어 있는 깊은 목결과 강렬한 전면 도어의 그래픽 패턴이 어우러져, 브루탈리즘 가구만의 독보적인 존재감을 보여줍니다. 네 개의 폴딩 도어를 갖추고 있어 내부에는 넉넉한 수납 공간과 실용적인 선반이 마련되어 있습니다.\n\n하단부 실버컬러 조화로 묵직한 우드 구조 속에 현대적이면서도 산업적인 질감을 더해주어, 전체 디자인에 포인트를 주는 동시에 세련되고 균형 잡힌 매력을 완성합니다.",
  "status": "available",
  "img": "images/products/DRO3Fhgkdko.jpg",
  "ig": "https://www.instagram.com/p/DRO3Fhgkdko/",
  "date": "November 19, 2025"
 },
 {
  "id": "DQ35nJXEWu2",
  "cat": "accessory",
  "name": "Italian Brevettato Floor Lamp",
  "size": "가로 29 세로 29 cm 높이 164cm",
  "desc": "1970년대 이탈리아에서 제작된 스페이스 에이지 플로어 램프입니다.\n70년대는 스페이스 에이지 시대적 배경이 반영된 시기로, 우주 탐사와 미래 기술에 대한 관심이 높았던 당시의 분위기가 이러한 미래적이고 진취적인 디자인을 탄생시켰습니다.\n그 당시 가전, 가구, 조명, 자동차, 패션 등 다양한 분야에서 이러한 스타일이 두드러지게 나타났으며, 이 램프 역시 우주 시대에서 영감을 받은 유선형 형태, 반짝이는 크롬 소재, 독특한 조형미 등 스페이스 에이지 시대의 특징을 잘 보여줍니다.\n\n중앙 기둥에 장착된 세 개의 조절식 헤드는 각각 좌우로 회전하며, 다양한 방향으로 빛을 비출 수 있어 다채로운 조명 연출이 가능합니다.\n\n이 조명은 기존의 디자인 틀을 깨고 혁신적이고 실험적인 스타일을 반영하여 디자인으로서 단순한 조명을 넘어 공간의 시각적 포인트 오브제로 활용할 수 있는 매력적인 조명입니다.",
  "status": "available",
  "img": "images/products/DQ35nJXEWu2.jpg",
  "ig": "https://www.instagram.com/p/DQ35nJXEWu2/",
  "date": "November 10, 2025"
 },
 {
  "id": "DPvoR_YkZ96",
  "cat": "cabinet",
  "name": "Poul Cadovis Royal System",
  "size": "가로 161cm 높이 149cm / 폭 22cm • 41cm",
  "desc": "1950년대에 덴마크 디자이너 Poul Cadovius가 디자인한 Royal System 선반입니다.\n\n해당 모델은 티크 목재로 제작되었으며 벽에 고정된 두 개의 수직 레일에 여러 개의 선반을 결합하여 구성된 모듈형 시스템입니다.\n\n이 시스템은 고정된 형태가 아니라 사용자의 필요에 따라 선반의 위치를 자유롭게 조절 가능하며 벽면에 부착되는 구조이기 때문에 바닥 공간을 차지하지 않아 거실, 서재, 사무실 등 다양한 공간에서 실용적으로 활용 가능합니다.\n\nPoul Cadvious는 세계 최초의 벽걸이형 모듈 가구 시스템 중 하나인 “Royal System“을 디자인하며 이름을 알렸으며,\n당시 가구 디자인에 혁신을 불러왔습니다.\n\nCadovius는 단순한 가구 디자이너를 넘어, 디자인과 기능의 경계를 허문 실용주의자로 평가받았습니다.",
  "status": "available",
  "img": "images/products/DPvoR_YkZ96.jpg",
  "ig": "https://www.instagram.com/p/DPvoR_YkZ96/",
  "date": "October 13, 2025"
 },
 {
  "id": "DPvoPcTEcz7",
  "cat": "table",
  "name": "Rosenthal Quadrondo Table",
  "size": "사이즈 문의",
  "desc": "",
  "status": "available",
  "img": "images/products/DPvoPcTEcz7.jpg",
  "ig": "https://www.instagram.com/p/DPvoPcTEcz7/",
  "date": "October 13, 2025"
 },
 {
  "id": "DPQ3BKAEaxn",
  "cat": "cabinet",
  "name": "Pilastro Modular Wall Unit Shelf",
  "size": "가로 148cm 높이 152cm 깊이 30cm | 선반 폭 20cm",
  "desc": "Pilastro에서 제작한 벽걸이 선반으로 1950~1960년대에 제작된 네덜란드 미드센추리 모더니즘 디자인을 대표하는 모듈형 시스템 가구입니다.\n기능성과 디자인 양면에서 높은 평가를 받고 있으며, 대표 디자이너인 Tjerk Reijenga의 작품으로도 잘 알려져 있습니다.\n\n해당 모델은 철제로 제작되었고 선반·캐비닛·벽 고정용 기둥 등 모든 부품이 모듈형으로 조립이 가능해 사용자의 공간과 용도에 맞게 자유롭게 조합 및 배치할 수 있습니다.\n\n라이트 그레이와 레드 컬러의 조합은 당시 미드센추리 디자인에서 자주 사용되던 색상 구성으로 산업적인 소재와 대담한 원색의 조화를 통해 기능성과 시각적 임팩트를 동시에 추구했던 그 당시 가구 디자인의 특징이 잘 드러납니다.",
  "status": "available",
  "img": "images/products/DPQ3BKAEaxn.jpg",
  "ig": "https://www.instagram.com/p/DPQ3BKAEaxn/",
  "date": "October 1, 2025"
 },
 {
  "id": "DPBEu8jEYuJ",
  "cat": "chair",
  "name": "VAD Trevarefabrikk Convair Lounge Chair",
  "size": "가로 80 세로 80 높이 70cm | 앉은 높이 40cm",
  "desc": "1970년대 노르웨이 디자이너 Oddmund Vad가 디자인한 Convair 라운지 체어입니다.\n\n스칸디나비아 빈티지 디자인의 대표적인 작품으로, 이 모델은 당시 인기 있던 항공기(Convair)에서 영감을 받아 디자인되었습니다.\n\n둥근 원형 쉘 구조와 몸을 감싸는 듯한 등받이, 넓은 좌석이 특징이며, 좌석은 투톤 컬러의 가죽으로 마감되어 있습니다.\n하단은 회전 가능한 원형 베이스로 구성되어, 실용성과 편안함을 동시에 갖추고 있습니다.\nOddmund Vad은 노르웨이의 가구 디자이너이자 제작자인 Vad사의 중요한 인물로, 특히 20세기 중반부터 활동하면서 스칸디나비아 디자인 전통과 현대적 감각을 결합한 작품으로 이름을 남겼습니다.",
  "status": "available",
  "img": "images/products/DPBEu8jEYuJ.jpg",
  "ig": "https://www.instagram.com/p/DPBEu8jEYuJ/",
  "date": "September 25, 2025"
 },
 {
  "id": "DOqAxYAETGg",
  "cat": "chair",
  "name": "IKEA Peanut Bench Stool",
  "size": "가로 110cm 세로 40cm 높이 42cm",
  "desc": "땅콩 모양의 라탄 벤치로, 1990년대 이케아에서 한정판으로 출시된 제품입니다.\n유려한 곡선미를 가진 라탄 좌석은 땅콩 특유의 잘록한 허리 라인이 돋보이며, 양쪽 넓은 곡면은 앉았을 때 편안함과 안정감을 제공합니다.\n삼각형 형태의 강철 와이어로 구성된 네 개의 다리는 벤치가 마치 공중에 떠 있는 듯한 가벼운 인상을 주며, 시각적으로도 독특한 조화를 이룹니다.\n하부 프레임은 스판 기능이 있어 다리를 접어 이동과 보관이 용이합니다.\n\n현재는 단종된 모델로, 하단에는 이케아 오리지널 라벨 스티커가 잘 보존되어 있습니다.",
  "status": "available",
  "img": "images/products/DOqAxYAETGg.jpg",
  "ig": "https://www.instagram.com/p/DOqAxYAETGg/",
  "date": "September 16, 2025"
 },
 {
  "id": "DOnwydVETv8",
  "cat": "chair",
  "name": "Vitra Louis 20 Chair",
  "size": "가로 47cm 세로 55cm 높이 84cm | 앉은 높이46cm",
  "desc": "프랑스 디자이너 Philippe Starck이 1991년에 디자인하고, 스위스 브랜드 Vitra에서 제작한 Louis 20 플라스틱 의자입니다.\n\n포스트모던 디자인과 실용성을 결합한 이 의자는 독창적인 형태와 시선을 끄는 디자인으로 주목받았으며, 스태킹이 가능해 공간 활용성에 용이합니다.\n\n좌석과 등받이는 단일 몰드로 성현된 폴리프로필렌으로 제작되었고, 뒷 프레임은 광택 처리된 알루미늄으로 구성되어 있습니다.\n\n입체적인 앞다리와 가늘고 유려한 곡선의 뒷다리는 필립스탁의 세심한 디테일과 조형적 감각이 잘 드러납니다.\n\n뉴욕 MoMA의 컬렉션에 포함되었으며 이 의자는 기능을 넘어선 하나의 디자인 아이콘으로 인정받고 있습니다.",
  "status": "available",
  "img": "images/products/DOnwydVETv8.jpg",
  "ig": "https://www.instagram.com/p/DOnwydVETv8/",
  "date": "September 15, 2025"
 },
 {
  "id": "DOnbd0DERB9",
  "cat": "table",
  "name": "Fritz Hansen Table",
  "size": "가로 120cm 세로 80cm 높이 71cm / 가로 115cm 세로 115cm 높이 71cm",
  "desc": "1968년, Piet Hein과 Bruno Mathsson이 디자인하고 덴마크 가구 브랜드 Fritz Hansen에서 제작한 다이닝 테이블입니다.\n\n당시 다양한 사이즈와 형태로 출시되었으며, 라미네이트 상판과 스틸 레그로 구성되어 단순하면서도 세련된 인상을 줍니다. 특히 상판이 공중에 떠 있는 듯한 느낌을 주는 ‘Span Leg’ 구조는 시각적인 가벼움과 함께 우수한 안정성을 제공하며, 분해와 조립 또한 용이합니다.\n\n입고된 제품은 1980년대에 생산된 오리지널 시리즈로, 상판 하단에는 Fritz Hansen의 정품 라벨이 부착되어 있습니다.\n\n오늘날에도 동일한 디자인으로 생산되고 있지만, 그당시 제작된 모델들은 소재감, 마감, 무게감에서 현대 제품과는 다른 깊이와 매력을 지니고 있습니다.",
  "status": "available",
  "img": "images/products/DOnbd0DERB9.jpg",
  "ig": "https://www.instagram.com/p/DOnbd0DERB9/",
  "date": "September 15, 2025"
 },
 {
  "id": "DODLXoOkXN9",
  "cat": "sofa",
  "name": "Cassina Maralunga 2 seater",
  "size": "가로 165cm 세로 80cm 높이 70cm | 착석 높이 45cm",
  "desc": "밀라노 출신 건축가 겸 산업 디자이너 비코 마지스트레티(Vico Magistretti)가 1973년에 디자인한 마라룽가 모델입니다.\n새롭게 가죽 교체되어 입고 되었으며 등받이 헤드레스트 부분 정상적으로 작동됩니다.\n\n까시나 모노그램과 오리지널 라벨 있는 모델입니다.",
  "status": "available",
  "img": "images/products/DODLXoOkXN9.jpg",
  "ig": "https://www.instagram.com/p/DODLXoOkXN9/",
  "date": "August 31, 2025"
 },
 {
  "id": "DNkebA4pytp",
  "cat": "sofa",
  "name": "Harvink Mission Sofa",
  "size": "가로 200cm 세로 112cm 높이 75cm | 좌석높이 45cm",
  "desc": "1980년대에 네덜란드의 유명 가구 디자이너 Jack Crebolder가 Harvink 가구 브랜드를 위해 디자인한 미션 소파 모델입니다.\n그 당시 하르빙크가 추구하던 스타일인 산업적이면서도 미니멀한 디자인 철학을 잘 보여주는 대표적인 작품 중 하나로 낮은 시트 포지션과 양옆 일체형 사이드 테이블이 특징입니다.\n\n오리지널 가죽으로 입고 되었습니다.",
  "status": "available",
  "img": "images/products/DNkebA4pytp.jpg",
  "ig": "https://www.instagram.com/p/DNkebA4pytp/",
  "date": "August 20, 2025"
 },
 {
  "id": "DMuaxgdO5Wi",
  "cat": "accessory",
  "name": "AKARI 23N • Isamu Noguchi",
  "size": "82cm × 120cm",
  "desc": "",
  "status": "available",
  "img": "images/products/DMuaxgdO5Wi.jpg",
  "ig": "https://www.instagram.com/p/DMuaxgdO5Wi/",
  "date": "July 30, 2025"
 },
 {
  "id": "DMpPBnKOJRf",
  "cat": "cabinet",
  "name": "Karl Andersson &amp; Söner Modular Wood Cabinet",
  "size": "가로 135cm 세로 55cm 높이 184cm",
  "desc": "1960년대, 덴마크의 대표적 모던 가구 디자이너 보르게 모겐센(Børge Mogensen)이 디자인하고, 스웨덴의 Karl Andersson &amp; Söner에서 제작한 모듈형 우드 캐비넷입니다.\n\n단정하면서도 구조적으로 완성도 높은 이 캐비넷은 북유럽 모던 디자인의 실용성과 조형미를 모두 갖추었습니다. 상·하단이 분리 가능한 2단 모듈형 구조로 되어 있으며, 슬라이딩 도어, 서류 정리용 수납칸, 그리고 다양한 컬러의 우드 트레이 등 기능성과 시각적 재미를 더하는 디테일이 특징입니다.\n\n모겐센은 기능적인 아름다움과 실용성, 구조적 안정성을 디자인의 중심에 두었던 디자이너로, 해당 모델에서도 그의 철학이 반영된 가구라 할 수 있습니다.",
  "status": "available",
  "img": "images/products/DMpPBnKOJRf.jpg",
  "ig": "https://www.instagram.com/p/DMpPBnKOJRf/",
  "date": "July 28, 2025"
 },
 {
  "id": "DMe7gr_OmcA",
  "cat": "accessory",
  "name": "Castelli Planta Coat Rack",
  "size": "사이즈 문의",
  "desc": "Schonbuch Quadro Wall Lamp",
  "status": "available",
  "img": "images/products/DMe7gr_OmcA.jpg",
  "ig": "https://www.instagram.com/p/DMe7gr_OmcA/",
  "date": "July 24, 2025"
 },
 {
  "id": "DMPaHxJuKau",
  "cat": "chair",
  "name": "Ecart International Sandow Chair",
  "size": "가로 42cm 세로 42cm 높이 82cm | 앉은 높이 46cm",
  "desc": "프랑스 모더니즘을 대표하는 건축가 르네 헤르스트(René Herbst, 1891–1982)가 1928년에 디자인한 모델로, 그의 상징적인 작품 중 하나입니다. 강철 튜브 프레임과 고무 탄성 코드(elastic rubber cord)로 구성된 이 의자는 1929년 파리 살롱 도톤에서 ‘Chaise Sandow’라는 이름으로 처음 공개되었습니다. ‘샌도우(Sandow)’라는 이름은 프랑스어로 좌판과 등받이에 사용된 고무 밴드에서 유래되었습니다.\n\n샌도우 의자는 1920년대 산업화의 흐름을 반영한 디자인으로 평가되며, 간결한 형태뿐만 아니라 당시로서는 혁신적인 소재와 구조를 활용함으로써 모던 디자인 역사에서 중요한 위치를 차지하고 있습니다.\n\n르네 헤르스트의 초기 생산된 모델은 뉴욕 현대미술관(MoMA)의 컬렉션에도 소장되어 있으며, 1980년대에 Ecart International에서 복각판을 제작해 다시금 조명을 받았습니다.\n\n샌도우 의자는 오늘날까지도 간결한 조형미로 많은 사랑을 받고 있으며, 빈티지 가구 아이콘으로 자리잡고 있습니다.\n\n입고된 이 모델은 Ecart의 에디션 제품이며 현재는 단종된 모델입니다.",
  "status": "available",
  "img": "images/products/DMPaHxJuKau.jpg",
  "ig": "https://www.instagram.com/p/DMPaHxJuKau/",
  "date": "July 18, 2025"
 },
 {
  "id": "DLmMrv2OoqJ",
  "cat": "chair",
  "name": "Cassina LC4 Longue Chair",
  "size": "가로 160cm 세로 58cm 높이 60cm",
  "desc": "1928년에 르 코르뷔지에(Le Corbusier), 피에르 쟈네레(Pierre Jeanneret), 샬롯 페리앙(Charlotte Perriand)이 까시나를 위해 공동 디자인한 LC4 라운지 체어입니다.\n\n오리지널 송치 가죽 시트와 곡선형 크롬 프레임, 블랙 에나멜 마감의 스틸 베이스로 구성되어 있으며, 상단 프레임은 기울기 조절이 가능해 사용자의 체형과 취향에 맞게 각도를 자유롭게 조정할 수 있습니다.\n\n인체의 곡선을 따라 유연하게 몸을 지지하는 구조로 설계되어 ’휴식의 기계‘라는 별칭을 지니며 20세기 모던 디자인을 대표하는 아이코닉한 작품으로 평가받고 있습니다.\n\n좋은 컨디션으로 입고되었습니다.",
  "status": "available",
  "img": "images/products/DLmMrv2OoqJ.jpg",
  "ig": "https://www.instagram.com/p/DLmMrv2OoqJ/",
  "date": "July 2, 2025"
 },
 {
  "id": "DK_2CNYJWlj",
  "cat": "chair",
  "name": "GALVANITAS S22 Stacking Chair",
  "size": "가로 53cm 세로 49cm 높이 79.5cm | 앉은 높이 47cm",
  "desc": "1960년대 네덜란드의 산업 디자인을 대표하는갈바니타스 s22 스태킹 체어입니다.\n\n독일의 Pagholz 압축 성형 합판을 사용하여 제작되었으며 독특한 프레임 다리 덕분에 가볍고 튼튼하며 기능성과 디자인을 모두 갖춘 디자인으로 평가받았습니다.\n\nPagholz는 나무와 레진 (합성 플라스틱 소재)을 고온 고압으로 압축해 만든 소재로, 내구성이 뛰어나고 습기나 충격에 강한 덕에 출시 당시 학교, 카페, 공공기관 등에서 널리  사용 되었습니다.\n\n여러점 입고되었습니다.",
  "status": "available",
  "img": "images/products/DK_2CNYJWlj.jpg",
  "ig": "https://www.instagram.com/p/DK_2CNYJWlj/",
  "date": "June 17, 2025"
 },
 {
  "id": "DKzTkNpJxIG",
  "cat": "sofa",
  "name": "Tecta F51 Bauhaus Sofa",
  "size": "가로 176cm 세로 64cm 높이 72cm | 앉은 높이 42cm",
  "desc": "Walter Gropius가 1920년대 초, 바이마르 바우하우스 교장실을 위해 디자인한 F51 바우하우스 소파입니다. 이후 독일 브랜드 Tecta에 의해 정식 라이선스로 복각 제작되었습니다.\n\nF51 모델은 기하학적이고 입체적인 구성으로, 당대의 건축적 실험 정신과 Gropius의 디자인 철학을 반영한 제품입니다.\n\n그로피우스는 풍성한 부피감의 쿠션과 함께, 팔걸이가 자유롭게 돌출되고 등받이가 바닥에 닿지 않는 혁신적인 구조를 도입했습니다. 이러한 독창적인 지지 방식은 시각적으로 공중에 떠 있는 듯한 인상을 주며, 당시로서는 매우 파격적인 디자인이었습니다.\n\n1980~90년대에 제작된 Tecta의 F51 모델은 블랙 라커 마감의 우드 프레임이 주를 이뤘고, 가죽이나 패브릭 커버 몇 가지 기본 색상만 제공되었으며 현재는 다양한 옵션을 선택 가능합니다.\n\nF51 소파는 시대의 변화에 따라 생산 방식과 취향을 반영하면서도 바우하우스 디자인 철학을 일관되게 계승해왔습니다.\n\n해당 제품은 1990년대 텍타에서 제작된 일체형 시트 디자인의 모델로, 현재 생산 중인 3인용 모델과는 다른 형태를 지니고 있습니다.\n\n하부는 블랙 라커 마감의 우드 프레임으로 제작되었으며, 초기형 모델은 중고 시장에서도 보기 드문 매물입니다.\n\n시트는 이태리 소가죽으로 새롭게 천갈이되어 입고되었습니다.",
  "status": "available",
  "img": "images/products/DKzTkNpJxIG.jpg",
  "ig": "https://www.instagram.com/p/DKzTkNpJxIG/",
  "date": "June 12, 2025"
 },
 {
  "id": "DKZHlXguMk0",
  "cat": "sofa",
  "name": "Cassina Maralunga 1 Seater Sofa",
  "size": "가로 95cm 세로 90cm 높이 70cm | 앉은 높이 48cm",
  "desc": "1973년에 비코 마지스트레티가 까시나를 위해 디자인한 마라룽가 1인 모델입니다.\n\n푹신한 폼 쿠션과 유연한 구조 덕분에 몸을 감싸는 듯한 착석감을 제공하며 등받이 각도 조절을 통해 머리 부분을 기대어 사용 가능합니다.\n\n헤드레스트 메카니즘은 정상 작동되며 까시나 모노그램과 라벨 모두 있는 모델입니다.\n\n해당 제품은 이태리 소가죽으로 천갈이되어 입고되었습니다.",
  "status": "available",
  "img": "images/products/DKZHlXguMk0.jpg",
  "ig": "https://www.instagram.com/p/DKZHlXguMk0/",
  "date": "June 2, 2025"
 },
 {
  "id": "DKHGg9-On_a",
  "cat": "chair",
  "name": "Castelli DSC 106",
  "size": "가로 56cm 세로 55cm  높이 78cm | 앉은 높이 45cm",
  "desc": "이탈리아의 대표적인 가구 브랜드인 아노니마 카스텔리에서 1965년에 출시한 dsc106 모델입니다.\n\n1960년대에는 플라스틱과 같은 신소재를 활용한 혁신적인 디자인으로 주목받았으며, 튼튼한 내구성과 위로 쌓아올려 보관이 가능한 DSC 106 의자는 이탈리아의 은행, 관공서, 미술관 등에서 널리 사용되었습니다.\n\n접이식 책상이 장착되어 있는 조합으로 탈부착이 가능하며 활용도가 높은 의자입니다.\n패브릭은 천갈이되어 입고되었으며 좋은 컨디션 유지하고 있습니다.",
  "status": "available",
  "img": "images/products/DKHGg9-On_a.jpg",
  "ig": "https://www.instagram.com/p/DKHGg9-On_a/",
  "date": "May 26, 2025"
 },
 {
  "id": "DJd6sa9J38Z",
  "cat": "cabinet",
  "name": "Kinnarps Oak Cabinet",
  "size": "가로 80cm 세로 41cm 높이 60cm",
  "desc": "1970년대 스웨덴 가구 브랜드 Kinnarps에서 제작한 오크 나무 소재의 캐비닛입니다.\n2단 서랍 구조로 구성되어 실용적인 수납이 가능하며, 하단 서랍은 자바라식 도어가 적용되어 열고 닫을 때의 부드러운 움직임과 깔끔한 마감이 돋보입니다.\n\n1942년 Evy와 Jarl Andersson 부부가 킨나르프의 목재 공장을 인수하여 Kinnarps를 설립하였습니다. 초기에는 건축가를 위한 맞춤형 가구를 제작하였으며, 1943년부터 스웨덴 정부에 가구를 공급하기 시작했습니다.\n\nKinnarps는 현재도 활발히 운영 중인 스웨덴의 대표적인 가구 브랜드로 1942년에 설립된 이후, 사무용 가구를 중심으로 교육 및 의료 환경까지 아우르는 통합 인테리어를 제공하며 성장해왔습니다.",
  "status": "available",
  "img": "images/products/DJd6sa9J38Z.jpg",
  "ig": "https://www.instagram.com/p/DJd6sa9J38Z/",
  "date": "May 10, 2025"
 },
 {
  "id": "DJEAmEQJFVZ",
  "cat": "chair",
  "name": "Young International Flyer Chair",
  "size": "가로 83cm 세로 83cm 높이 100cm | 앉은 높이 36cm",
  "desc": "1980년대에 Pierre Mazairac와 Karel Boonzaaijer가 네덜란드 가구 브랜드 Young International을 위해 디자인한 Flyer 모델 의자입니다.\n\n간결하지만 얇고 선명한 하부 프레임과 가죽의 조화를 통해 절제됨과 동시에 존재감 있는 형태가 특징입니다.\n\n그들의 철학은 Dieter Rams와 같은 기능주의 디자이너들의 영향을 받았고, Flyer Chair는 당시 사무실과 가정에서 모두 활용될 수 있도록 디자인된 디자인으로 기능성과 조형미의 조화를 추구했습니다.\n\nFlyer 소파는 낮고 넓은 시트 비율을 갖고 있어 앉았을 때 안정감을 주며, 공간에 배치했을 때는 마치 작은 건축 오브제 처럼 느껴집니다.",
  "status": "available",
  "img": "images/products/DJEAmEQJFVZ.jpg",
  "ig": "https://www.instagram.com/p/DJEAmEQJFVZ/",
  "date": "April 30, 2025"
 },
 {
  "id": "DI6FW_opMsn",
  "cat": "chair",
  "name": "Cassina AEO Armchair",
  "size": "가로 79cm x 세로 75cm x 높이 107cm | 앉은 높이 45cm",
  "desc": "이탈리아 디자이너 파올로 데가넬로가 1973년 까시나를 위해 디자인한 AEO 암체어입니다.\n\n1960~70년대 이탈리아에서는 기능 중심적이고 상업화된 디자인에 대한 반발로 철학적이고 사회적인 메시지를 담은 디자인 운동(Radical Design)이 전개되었으며, AEO 모델은 기존 암체어의 고정관념을 깨는 실험적인 디자인으로 시대적 특성이 반영된 디자인 중 하나입니다.\n\n이 암체어 편안함보다는 비대칭적인 구조, 노출 프레임 등 이 주는 외관이 특징이며, 출시 당시 소비자가 직접 조립할 수 있도록 설계된 점은 당시로서는 매우 파격적인 접근이었습니다.\n\n이러한 점은 “디자인은 무조건적인 기능을 위한 것이 아니다”라는 비판적 메시지를 담고 있으며,\n가구를 단순한 소비재가 아닌 소비자도 제작과 해석의 주체로 참여할 수 있는 오브제로 바라본 Radical Design의 철학이 잘 반영되어 있습니다.\n\nAEO 암체어는 실용성보다는 메시지를 전달하는데 초점을 맞춘 사회적 실험이자 예술적 시도이며,\n기능성과 형태의 경계를 허무는 디자인으로 평가받습니다.\n\nRadical Design은 이후 Memphis 그룹(1980년대)과 포스트모더니즘 디자인, 나아가 오늘날의 실험적 디자인에까지 영향을 미쳤으며, 지금도 우리에게 “왜 디자인은 이래야만 하는가?”라는 근본적인 질문을 던지게 합니다.",
  "status": "available",
  "img": "images/products/DI6FW_opMsn.jpg",
  "ig": "https://www.instagram.com/p/DI6FW_opMsn/",
  "date": "April 26, 2025"
 },
 {
  "id": "DIx6PoaJR2V",
  "cat": "chair",
  "name": "Kengu Lounge Armchair",
  "size": "가로 65cm 세로 64cm 높이 80cm | 앉은 높이 40cm",
  "desc": "1970년대에 노르웨이 가구 브랜드 Rybo Rykken &amp; Co에서 제작한 Kengu 라운지 체어입니다.\n\n스칸디나비아 디자인을 대표하는 클래식한 디자인으로 프레임은 곡선 형태가 돋보이며 좌석과 등받이는 편안한 쿠션으로 구성되어 안정적이고 편안한 착석감을 제공합니다.\n너도밤나무로 제작되었습니다.",
  "status": "available",
  "img": "images/products/DIx6PoaJR2V.jpg",
  "ig": "https://www.instagram.com/p/DIx6PoaJR2V/",
  "date": "April 22, 2025"
 },
 {
  "id": "DIs0Wu8pS5x",
  "cat": "chair",
  "name": "Matteo Grassi Korium Armchair",
  "size": "가로 63cm 세로 46cm 높이 86cm | 앉은 높이 46cm",
  "desc": "1979년 Tito Agnoli가 Matteo Grassi를 위해 디자인한 Korium 가죽 암체어입니다.\n\n1880년대 승마용 안장과 가죽 제품 제작으로 시작해 고급 안장 가죽과 정교한 디자인을 결합한 가구로 명성을 얻은 이탈리아 브랜드로, Korium 모델 역시 고급 통가죽으로 제작되어 세련된 실루엣과 편안한 착석감을 제공합니다.\n\n가죽은 정교하게 스티칭되어 있으며, Matteo Grassi의 전통적인 가죽 기술이 적용되어 마감이 정교하고 섬세합니다. 외관적으로 팔걸이, 등받이, 다리가 하나의 유기적인 흐름으로 연결되는 독창적인 구조로, 부드러운 곡선미와 존재감을 동시에 전달합니다.\n\n스툴과 함께 여러점 입고되었습니다.",
  "status": "available",
  "img": "images/products/DIs0Wu8pS5x.jpg",
  "ig": "https://www.instagram.com/p/DIs0Wu8pS5x/",
  "date": "April 21, 2025"
 },
 {
  "id": "DHseAzdJv1J",
  "cat": "cabinet",
  "name": "Wood Modular Cabinet",
  "size": "가로 312cm 세로 35cm 높이 165cm",
  "desc": "1970년대 제작된 모듈형 우드 캐비닛입니다.\n네덜란드 모더니즘을 반영한 디자인으로, 티크 나무, 유기적인 형태, 그리고 모듈식 기능성이 특징입니다.\n기하학적인 패턴이 적용되어 열린 공간과 닫힌 수납부가 조화를 이루며 강렬한 시각적 효과를 형성하며 당시의 대담한 기하학적 미학과 기능적 다용성을 보여주는 가구입니다.\n\n선반과 슬라이딩 패널을 자유롭게 조합할 수 있는 모듈형 시스템을 갖추어 다양한 방식으로 수납이 가능하며 벽에 기대지 않고 자립할 수 있도록 설계되어 공간을 나누는 파티션 역할도 수행합니다.\n\n이 캐비닛은 티크 나무로 제작되었으며 네 개의 섹션을 연결하여 공간에 맞게 모듈형태로 사용할 수 있습니다.",
  "status": "available",
  "img": "images/products/DHseAzdJv1J.jpg",
  "ig": "https://www.instagram.com/p/DHseAzdJv1J/",
  "date": "March 27, 2025"
 },
 {
  "id": "DHGXZGPJwPp",
  "cat": "sofa",
  "name": "Cassina Maralunga 2 seater",
  "size": "가로 165cm 세로 80cm 높이 70cm | 착석높이 45cm",
  "desc": "1970년대 지안 카를로 피레티가 이탈리아 Cassina를 위해 디자인한 마라룽가입니다.\n간결한 디자인과 편안함으로 잘 알려진 소파로 꾸준히 사랑받고 있는 모델입니다.\n\n해당 제품은 모노그램과 라벨이 모두 존재하며 헤드레스트 체인도 정상적으로 작동됩니다.\n\n이 소파는 이태리 소가죽으로 업홀스터리 되었습니다.",
  "status": "available",
  "img": "images/products/DHGXZGPJwPp.jpg",
  "ig": "https://www.instagram.com/p/DHGXZGPJwPp/",
  "date": "March 12, 2025"
 },
 {
  "id": "DGmnifqpg3J",
  "cat": "sofa",
  "name": "Ligne Roset Kashima Sofa",
  "size": "가로 160cm 폭 95cm 높이 75cm",
  "desc": "1970년대에 프랑스 디자이너 미셸 뒤카루아(Michel Ducaroy)가 리네 로제(Ligne Roset)를 위해 디자인한 Kashmia 소파 입니다.\n\n그의 대표작인 Togo 소파와 디자인적 유사성을 가지면서도, Kashima만의 퀼팅 버튼 디테일을 유지하며 보다 클래식한 감성을 더했습니다.\n\n소파 전체가 고밀도 폼으로 제작되어 뛰어난 내구성을 자랑하며 오랜 시간 사용해도 편안하고 곡선형 시트 디자인이 적용되어 사용자가 몸을 기댈 때 자연스럽게 안락함을 느낄 수 있도록 설계되었습니다.",
  "status": "available",
  "img": "images/products/DGmnifqpg3J.jpg",
  "ig": "https://www.instagram.com/p/DGmnifqpg3J/",
  "date": "February 27, 2025"
 },
 {
  "id": "DGhvNE9pBvK",
  "cat": "chair",
  "name": "Harvink Bentwood Chair",
  "size": "가로 43 cm 세로 54 cm 높이 84cm | 착석높이 47cm",
  "desc": "1980년대에 Ruud Jan Kokke가 Harvink을 위해 디자인한 의자입니다.\n\n나무합판을 구부려 바디 프레임에 고정시키는 방식으로 제작되었으며, 가볍고 내구성이 뛰어난 것이 특징입니다.\n\n뤼드 얀 콕케는 네덜란드 출신의 디자이너로, 미니멀하면서도 기능적인 디자인을 특징으로 하는 가구를 제작해왔으며, 이 의자는 그의 대표적인 디자인으로 잘 알려졌습니다.",
  "status": "available",
  "img": "images/products/DGhvNE9pBvK.jpg",
  "ig": "https://www.instagram.com/p/DGhvNE9pBvK/",
  "date": "February 25, 2025"
 },
 {
  "id": "DGfWwJnJ6vT",
  "cat": "table",
  "name": "Herman Miller Eames Table",
  "size": "가로 80cm 세로 80cm 높이 73cm | 상판 두께 3cm",
  "desc": "Charles &amp; Ray Eames가 Vitra를 위해 디자인한 모듈형 테이블 입니다.\n1964년 첫 출시 후 오늘날까지 Vitra에서 꾸준히 생산되는 모델로, 미니멀하면서도 기능적인 디자인입니다.\n\n다양한 크기와 마감 옵션으로 사무실, 회의실, 가정 등 다양한 환경에서 활용할 수 있어 대중적으로 인기를 끌었습니다.",
  "status": "available",
  "img": "images/products/DGfWwJnJ6vT.jpg",
  "ig": "https://www.instagram.com/p/DGfWwJnJ6vT/",
  "date": "February 25, 2025"
 },
 {
  "id": "DGVQ3J9pawR",
  "cat": "sofa",
  "name": "Cassina Maralunga Sofa",
  "size": "사이즈 문의",
  "desc": "까시나 마라룽가 소파는 1973년 비코 마지스트레티가 디자인한 이탈리아 모던 디자인의 아이콘 중 하나입니다.\n\nCassina는 종종 제품 이름을 이탈리아 지역명이나 문화적 요소에서 차용하는 경향이 있으며\n“Maralunga“라는 이름은 이탈리아 북부 지역에 있는 작은 마을 이름에서 유래되었습니다.\n\n소파의 골조는 견고한 강철 프레임으로 제작되어 튼튼한 내구성을 자랑하고 고급 자재를\n사용한 덕분에 마라룽가 소파는 편안함과 내구성 모두를 갖춘 클래식 가구로 평가받았습니다.\n\n각 소파는 까시나 라벨과 모노그램이 있는 제품이며, 오토만을 포함하여 이태리 소가죽으로 업홀되어 입고되었습니다.",
  "status": "available",
  "img": "images/products/DGVQ3J9pawR.jpg",
  "ig": "https://www.instagram.com/p/DGVQ3J9pawR/",
  "date": "February 21, 2025"
 },
 {
  "id": "DGQBJHtJmz3",
  "cat": "chair",
  "name": "Kusch&amp;Co Flori Wood Chair",
  "size": "사이즈 문의",
  "desc": "1980년대 Kusch&amp; Co가 제작한 플로리 체어입니다.\n곡선형의 두꺼운 나무 합판과 크롬 스틸 프레임 조합으로 매력적이고 편안한 착석감을 제공합니다.\n\n스태킹이 가능하여 보관에도 용이한 의자입니다.\n\n가로 49cm 세로 55cm 높이 83cm | 착석높이 46cm\n\n수량 20점",
  "status": "available",
  "img": "images/products/DGQBJHtJmz3.jpg",
  "ig": "https://www.instagram.com/p/DGQBJHtJmz3/",
  "date": "February 19, 2025"
 },
 {
  "id": "DD6xTB5JsJK",
  "cat": "sofa",
  "name": "Desede DS-2011 Sofa 2 Seater",
  "size": "Width 195cm Depth 80cm Height 81cm | Seating Height 40cm",
  "desc": "1980년대 초반 스위스 가구 브랜드 De Sede에서 제작한 DS 2011 모델 소파입니다.\n\n단단한 강철 프레임 구조와 다양한 원단 옵션으로 출시된 이 소파는 컴팩트한 형태로 1980년대 미니멀리즘과 현대적인 미학을 잘 반영하고 있습니다. 구부러진 팔걸이가 특징으로, 묵직하면서도 시크한 분위기를 연출합니다.\n\n이 제품은 이태리 소가죽으로 업홀스터리 되었으며, 내부의 오리지널 라벨과 로고가 모두 보존된 상태입니다.\n\n2,3인 사이즈 여러점 재고 있습니다.",
  "status": "available",
  "img": "images/products/DD6xTB5JsJK.jpg",
  "ig": "https://www.instagram.com/p/DD6xTB5JsJK/",
  "date": "December 23, 2024"
 },
 {
  "id": "DDwUWmdJdIA",
  "cat": "chair",
  "name": "Artifort Ben Chair",
  "size": "Width 72cm Depth 78cm Height 75cm | Seating Height 42cm",
  "desc": "1970년대에 프랑스 디자이너 피에르 폴랭(Pierre Paulin)이 네덜란드 가구 브랜드 Artifort를 위해 디자인한 벤 체어입니다.\n\n유기적 곡선을 특징으로 하며, 단순하지만 독창적인 형태가 공간에서 돋보이는 디자인으로\n폴랭의 디자인 철학인 &quot;형태는 기능을 따른다&quot;를 잘 반영한 의자입니다.\n\n부클 소재로 업홀되어 시각적으로 따뜻하고 부드러운 촉감과 편안한 착석감을 제공합니다.",
  "status": "available",
  "img": "images/products/DDwUWmdJdIA.jpg",
  "ig": "https://www.instagram.com/p/DDwUWmdJdIA/",
  "date": "December 19, 2024"
 },
 {
  "id": "DB8f7ILpqqx",
  "cat": "accessory",
  "name": "Luceplan Titania Ceiling Lamp",
  "size": "Width 70cm Length 30cm Depth 8cm",
  "desc": "이탈리아 디자이너 알베르토 메다&amp;파올로 리촐리가 1989년에 Luceplan을 위해 디자인한 Titania 조명입니다.\n\n가벼우면서도 강한 알루미늄 베이스와 컬러 필터 시스템으로 잘 알려진 모델입니다. 타원형 모양에 여러 겹의 얇은 알루미늄으로 이루어져 있어 공중에 떠 있는 듯한 가벼운 느낌을 주며, 컬러 필터를 통해 다양한 빛이 연출됩니다.\n\n갓 양쪽에 설치된 컬러 필터를 교체하여 조명의 색조를 다양하게 연출할 수 있습니다.\n해당 제품은 보라와 파랑 필터가 있는 모델입니다.",
  "status": "available",
  "img": "images/products/DB8f7ILpqqx.jpg",
  "ig": "https://www.instagram.com/p/DB8f7ILpqqx/",
  "date": "November 4, 2024"
 },
 {
  "id": "DB0hYqQJoSZ",
  "cat": "chair",
  "name": "Metaform Circle Chair",
  "size": "Width 52cm Depth 52cm Height 78cm |  Seating Height 46cm",
  "desc": "1980년대에 Karel Boonzaadjer와 Pierre Mazairac이 디자인하고 네덜란드 가구회사 Metaform에서 제작한 Circle 의자입니다.\n\n미니멀리즘과 포스트모던 디자인을 결합한 독특한 스타일로, 원형 디자인을 모티프로 하여 ’Circle(원)‘이라는 이름이 붙었으며, 포스트모던 스타일의 간결한 선과 형태를 잘 보여줍니다.\n\n금속으로 이루어진 튜브 프레임은 슬림하면서도 견고하게 설계되었으며 넓은 좌판은 편안한 착석감을 제공합니다.",
  "status": "available",
  "img": "images/products/DB0hYqQJoSZ.jpg",
  "ig": "https://www.instagram.com/p/DB0hYqQJoSZ/",
  "date": "November 1, 2024"
 },
 {
  "id": "DBqL8PqppwW",
  "cat": "sofa",
  "name": "Auping Cleopatra Daybed",
  "size": "Width 198cm Depth 84cm Height 38cm",
  "desc": "1953년 Dick Cordemeijer가 네덜란드 가구회사 Auping을 위해 디자인한 클레오파트라 데이베드 입니다.\n침대와 소파 등 다목적 용도로 활용 가능하며 공간 활용도가 높은 가구입니다.\n\n데이베드의 하부는 강철 프레임과 견고한 스프링으로 구성되어 폼 베드를 안정적으로 지지합니다.\n베드는 부클 소재로 제작되었으며, 양쪽 끝 티크 나무가 있어 따듯하고 자연스러운 분위기를 연출합니다.",
  "status": "available",
  "img": "images/products/DBqL8PqppwW.jpg",
  "ig": "https://www.instagram.com/p/DBqL8PqppwW/",
  "date": "October 28, 2024"
 },
 {
  "id": "DBqLZ1JJMjd",
  "cat": "sofa",
  "name": "Maralunga 3 seater sofa",
  "size": "Width 236cm Depth 90cm Height 72cm | Seating Height 42cm",
  "desc": "1973년 비코 마지스트레티가 카시나를 위해 디자인한\n마라룽가 모델입니다.\n\n스트라이프 패턴이 들어간 오리지널 패브릭 원단으로\n우수한 컨디션 유지하고 있습니다.\n\n헤드레스트 부분 정상적으로 작동되며 모노그램과 라벨 모두 있습니다.",
  "status": "available",
  "img": "images/products/DBqLZ1JJMjd.jpg",
  "ig": "https://www.instagram.com/p/DBqLZ1JJMjd/",
  "date": "October 28, 2024"
 },
 {
  "id": "DAsqoE7P26x",
  "cat": "chair",
  "name": "Kembo Wood Dotted Chair",
  "size": "Width 42cm Depth 45cm Height 80cm | Seating Height 44cm",
  "desc": "네덜란드 가구 제조업체 Kembo에서 제작한 도트 무늬 우드 체어입니다.\n\n간단한 구조의 스틸 프레임과 견고한 나무 등받이로\n제작되었으며 스태킹이 가능합니다.\n\n여러점 보유 중 입니다.",
  "status": "available",
  "img": "images/products/DAsqoE7P26x.jpg",
  "ig": "https://www.instagram.com/p/DAsqoE7P26x/",
  "date": "October 4, 2024"
 },
 {
  "id": "DAX7oX5pMfK",
  "cat": "table",
  "name": "Gatti Nesting Table, 1970s",
  "size": "Width 52cm Depth 52cm Height 26cm",
  "desc": "1967년 마리오 벨리니(Mario Bellini)가 C&amp;B Italia(후에 B&amp;B Italia)를 위해 디자인한 Gatti 테이블 입니다.\n\n4개의 테이블을 구성으로 플라스틱 소재로 제작되었으며, 사용자의 용도에 맞게 층층이 쌓아 올려 사용하거나 겹쳐서 보관할 수 있어 공간 활용에 실용적인 테이블입니다.\n\n해당 모델은 1970년대에 생산된 모델로 이탈리아 B&amp;B 로고가 각인되어있습니다.",
  "status": "available",
  "img": "images/products/DAX7oX5pMfK.jpg",
  "ig": "https://www.instagram.com/p/DAX7oX5pMfK/",
  "date": "September 26, 2024"
 },
 {
  "id": "DAXv-DQJVr1",
  "cat": "accessory",
  "name": "Space Age Wall Lamp by Polam, 1970s",
  "size": "Width 12cm Depth 10cm Height 28cm",
  "desc": "1970년대에 네덜란드 조명회사 폴람(Polam)에서 제작한 크롬 벽 조명 입니다.\n\n브라켓을 벽에 고정 후 본체를 결합하는 방식으로 360도 회전이 가능하며\n상하로 빛을 비추는 구조입니다.",
  "status": "available",
  "img": "images/products/DAXv-DQJVr1.jpg",
  "ig": "https://www.instagram.com/p/DAXv-DQJVr1/",
  "date": "September 25, 2024"
 },
 {
  "id": "DANmef7JyGI",
  "cat": "chair",
  "name": "Knoll Armchair, 1960s",
  "size": "Width 70cm Depth 78cm Height 79cm | Seating Height 41cm",
  "desc": "1960년대 Walter Knoll이 디자인한 1인 암체어입니다.\n너도밤나무 소재로 제작되었으며 오리지널 패브릭으로 입고 되었습니다.",
  "status": "available",
  "img": "images/products/DANmef7JyGI.jpg",
  "ig": "https://www.instagram.com/p/DANmef7JyGI/",
  "date": "September 22, 2024"
 },
 {
  "id": "C_pcDxPJHqP",
  "cat": "table",
  "name": "Bruno Rey Rectangle Table",
  "size": "Width 140cm Depth 80cm Height 74cm / Width 160cm Depth 80cm Height 74cm",
  "desc": "1970년대에 브루노 레이가 독일의 Kusch+ Co를 위해 디자인한 너도밤나무 테이블입니다. 상판은 라미네이트 소재로 제작되었으며 튼튼하고 내구성이 우수한 테이블입니다.\n\n너도밤나무의 따뜻한 색감과 자연스러운 결은 아늑한 실내 환경에 잘 어울리며, 상업적인 공간에서도 효과적으로 활용될 수 있습니다. 거실, 서재, 침실뿐만 아니라 카페나 사무실 등 다양한 공간에서도 편안하고 안정적인 분위기를 연출할 수 있습니다.\n\n해당 테이블 여러점 입고 되었습니다.",
  "status": "available",
  "img": "images/products/C_pcDxPJHqP.jpg",
  "ig": "https://www.instagram.com/p/C_pcDxPJHqP/",
  "date": "September 8, 2024"
 },
 {
  "id": "C_cTanzpYFC",
  "cat": "table",
  "name": "Bruno Rey Round Table",
  "size": "사이즈 문의",
  "desc": "스위스 디자이너 Bruno Rey가 1970년대에 Dietiker를 위해 디자인한 라운드 다이닝 테이블입니다.\n\n테이블 상판은 내구성이 우수한 라미네이트 소재로 제작되었으며, 버건디 색상의 금속 커넥터와 4개의 나무 다리를 결합하여 디자인되었습니다.\n\n레이의 금속커넥터는 당시 혁신적인 디자인으로 조립과 해체가 용이하고 구조적으로 강한 지지대를 제공하였습니다.\n\n덕분에 테이블 다리와 상판이 튼튼하게 결합되어, 오랜\n시간 동안 안정적인 사용이 가능했으며, 구조적으로도 흔들림이 적습니다.\n\n브루노 레이의 테이블은 시간이 지나도 여전히 많은 사람들에게 사랑받는 클래식한 디자인으로, 단순하면서도 세련된 미학을 갖추고 있어 오늘날 다양한 실내 공간에서도 잘 어울리는 디자인입니다.\n\nDiameter 60• 70 • 80cm Height 74cm\n\n20점 입고되었습니다.",
  "status": "available",
  "img": "images/products/C_cTanzpYFC.jpg",
  "ig": "https://www.instagram.com/p/C_cTanzpYFC/",
  "date": "September 2, 2024"
 },
 {
  "id": "C-PO5bPpsqb",
  "cat": "chair",
  "name": "David Rowland 40/4 Stacking Chairs",
  "size": "Width 48cm Depth 45cm Height 76 cm | Seating Height 45cm",
  "desc": "1964년 David Rowland가 덴마크의 Howe Europe을 위해 디자인한 40/4 스태킹 체어입니다.\n\n모델 ’40/4‘는 40개의 의자를 40 피트(122cm) 높이까지 쌓을 수 있다는 점에서 이름이 유래되었습니다. 이는 공간 절약 측면에서 매우 유용하여, 특히 대규모 회의실, 강당, 교육 시설 등에서 주로 사용되었습니다.\n\n40/4 모델은 매우 편안한 착석감과 견고한 내구성을 자랑하며, 혁신성과 미니멀리즘 디자인으로 주목받았습니다.\n\n그 당시 매우 현대적이고 기능적인 디자인으로 평가되었고 여러 디자인 상을 수상하며 전 세계의 여러 디자인 박물관에 전시되었습니다.",
  "status": "available",
  "img": "images/products/C-PO5bPpsqb.jpg",
  "ig": "https://www.instagram.com/p/C-PO5bPpsqb/",
  "date": "August 3, 2024"
 },
 {
  "id": "C964c3QJ0yw",
  "cat": "chair",
  "name": "Kembo Stacking Chair",
  "size": "사이즈 문의",
  "desc": "",
  "status": "available",
  "img": "images/products/C964c3QJ0yw.jpg",
  "ig": "https://www.instagram.com/p/C964c3QJ0yw/",
  "date": "July 27, 2024"
 },
 {
  "id": "C9hH0vlpCxw",
  "cat": "chair",
  "name": "Thonet S320, 1980s",
  "size": "61 x 61 x h 79cm | Seating Height 46cm",
  "desc": "1980년대 Wulf Schneider &amp; Ulrich Boehme가 Thonet을 위해 디자인한 s320 모델입니다.\n\n너도밤나무 베이스와 스틸 프레임으로 이루어진 이 모델은 토넷의 전통적인 벤트우드 기술을 활용하여 제작되었으며\n곡선적이고 매끄러운 형태로 잘 알려져있습니다.\n\ns320 모델은 사용자에게 편안하고 안정적인 착좌감을 제공하며 뛰어난 완성도와 내구성 덕분에 주거 공간 뿐만 아니라 상업적인 장소에서도 널리 사용되고 있습니다.\n\n의자는 스태킹이 가능하여 사용하지 않을 때 편리하게 보관할 수 있습니다.",
  "status": "available",
  "img": "images/products/C9hH0vlpCxw.jpg",
  "ig": "https://www.instagram.com/p/C9hH0vlpCxw/",
  "date": "July 17, 2024"
 },
 {
  "id": "C9T8yZdJdDT",
  "cat": "accessory",
  "name": "Stilnovo Zagar Floor Lamp, 1980s",
  "size": "Width 33 cm Depth 24 cm Height 184 cm",
  "desc": "1980년대 Sergio Carpani가 이탈리아의 Stilnovo를 위해 디자인한 Zagar 플로우 램프입니다.\n\n이 모델은 할로겐 빛이 내장된 헤드부분의 틸팅 각도가 90도까지 조절되어 빛의 각도에 따라 다양한 분위기를 연출하며, 디밍 스위치를 통해 밝기 조절이 가능합니다.\n\nZagar 램프의 기둥은 날카로운 윤곽을 가진 직사각형 형태로, 표면에는 연속된 홈이 있어 독특한 시각적 효과를 줍니다. 전체적으로 램프는 검은색으로 마감되어 있으며, 일부 디테일은 빨간색으로\n강조되어 있어 시선을 사로잡습니다.\n\nZagar 플로어 램프는 현대적이고 독창적인 조명 솔루션을 제공하여 공간 속 창의성과 세련된 느낌을 더할 수 있는 조명입니다.",
  "status": "available",
  "img": "images/products/C9T8yZdJdDT.jpg",
  "ig": "https://www.instagram.com/p/C9T8yZdJdDT/",
  "date": "July 11, 2024"
 },
 {
  "id": "C9PGznVpxCs",
  "cat": "table",
  "name": "Quattro Gatti Coffee Tables by Mario Bellini for B&amp;B Italia, 1960s",
  "size": "사이즈 문의",
  "desc": "",
  "status": "available",
  "img": "images/products/C9PGznVpxCs.jpg",
  "ig": "https://www.instagram.com/p/C9PGznVpxCs/",
  "date": "July 10, 2024"
 },
 {
  "id": "C8_xidiJ0cH",
  "cat": "accessory",
  "name": "Series UP 2000 UP7 Foot",
  "size": "width 67cm | depth 162cm | height 83cm",
  "desc": "1969년에 Gaetano Pesce가 디자인한\nB&amp;B Italia의 Series UP 2000 UP7 Foot 입니다.\n\n1960년대 후반과 70년대 초반에는 디자인에서 혁신과 실험이 매우 중요한 위치를 차지했습니다.\n디자이너들은 새로운 재료와 형태를 탐구하였으며 이러한 시대적 맥락에서 발바닥 모양의 의자가 탄생할 수 있었고, UP7은 Pesce가 새로운 형태와 표현을 찾기 위해 실험한 결과물입니다.\n\nPesce는 이 의자를 디자인할 때 기존의 의자 형태에서 벗어나고자 했습니다.\n발바닥 모양의 독특한 디자인은 그의 창의적인 접근을 반영하며, 기존의 관습을 깨고 새로운 시각을 제시하는 것을 목표로 하였습니다.\n\n더나아가, 발바닥 모양은 시각적인 그 자체로도 흥미롭지만, 높은 등받이와 깊은 좌석을 제공하여 사용자에게 편안한 안락함을 제공합니다.\n\n가구는 종종 기능성 뿐만 아니라 예술적 표현 수단으로서도 간주됩니다. UP7은 단순한 의자가 아닌 공간에 존재하는 예술 작품으로서의 가치를 더합니다.",
  "status": "available",
  "img": "images/products/C8_xidiJ0cH.jpg",
  "ig": "https://www.instagram.com/p/C8_xidiJ0cH/",
  "date": "July 4, 2024"
 },
 {
  "id": "C86a5-BONFe",
  "cat": "sofa",
  "name": "Cassina Maralunga 3 seater",
  "size": "236 x 90 x h72 cm | Seating Height 42 cm",
  "desc": "1973년 비코 마지스테티가 까시나를 위해 디자인한 마라룽가 3시터 입니다.\n\n오리지널 패브릭의 블랙 그레이 컬러와 은은한 스트라이프 패턴은 가죽 마라룽가와는 사뭇 다른 분위기를 연출합니다.\n\n원단의 헤짐이나 찢어진 부분없이 우수한 컨디션으로 입고되었으며, 등받이 체인 메카닉 부분도 정상으로 작동합니다.\n\n해당 제품은 쿠션 하단부 까시나 모노그램 로고와 오리지널 라벨 모두 부착되어 있습니다.",
  "status": "available",
  "img": "images/products/C86a5-BONFe.jpg",
  "ig": "https://www.instagram.com/p/C86a5-BONFe/",
  "date": "July 2, 2024"
 },
 {
  "id": "C6-bP55JmIS",
  "cat": "table",
  "name": "Pastoe Cees Braakman Dinning Table Set",
  "size": "사이즈 문의",
  "desc": "1970년대 Cees Braakman이 Pastoe를 위해 디자인한 다이닝 테이블 세트입니다.\n\n테이블 상판은 얼룩에 강한 포미카 재질의 테이블로 제작되었으며, 상판은 확장 가능하여 최대 6~8인까지 수용 가능합니다.\n\n다이닝 테이블 세트는 의자를 포함하여 대체로 깔끔한 라인, 기능적인 형태, 그리고 미니멀한 디자인으로 미드센츄리 모던의 원칙을 구현합니다.\n\n4개의 다이닝체어는 프레임의 시크함과 원단의 포근함을 더해 새롭게 업홀 되었습니다.\n\nBraakman은 1940년대부터 1970년대까지 Pastoe와 함께 일하며 브랜드의 현대적 디자인 방향에 크게 기여했습니다.",
  "status": "available",
  "img": "images/products/C6-bP55JmIS.jpg",
  "ig": "https://www.instagram.com/p/C6-bP55JmIS/",
  "date": "May 14, 2024"
 },
 {
  "id": "C6c75EDpWq4",
  "cat": "table",
  "name": "Quadrondo Dining Table by Rosenthal, 1980s",
  "size": "사이즈 문의",
  "desc": "",
  "status": "available",
  "img": "images/products/C6c75EDpWq4.jpg",
  "ig": "https://www.instagram.com/p/C6c75EDpWq4/",
  "date": "May 1, 2024"
 },
 {
  "id": "C5iMSg0uIY3",
  "cat": "table",
  "name": "TECTA M1 Table",
  "size": "Width 188 cm / Height 74 cm / Depth 148 cm",
  "desc": "",
  "status": "available",
  "img": "images/products/C5iMSg0uIY3.jpg",
  "ig": "https://www.instagram.com/p/C5iMSg0uIY3/",
  "date": "April 9, 2024"
 },
 {
  "id": "C5X1B5SOZ-8",
  "cat": "accessory",
  "name": "Serpente Floor Lamp",
  "size": "사이즈 문의",
  "desc": "Manufacturer Martinelli Luce (Italy)\nDesigned by Elio Martinelli\nPeriod 1965s ~\nDimensions D55 x H120cm\nCondition Signs of Marks\n\n이탈리아 산업 디자이너 엘리오 마르티넬리가 1965년에 디자인한 세르펜테 플로우 램프입니다.\n이태리어로 세르펜테는 뱀을 뜻하며, 미니멀한 디자인과 360도 회전 가능한 기능이 특징인 세르펜테 플로우 램프는 마치 뱀의 모습을 연상시킵니다. 해당 램프는 그 당시 혁신적인 소재 아크릴을 사용하여 제작하였고, 전통적인 램프 디자인과는 차별화되어 기능적인면과 더불어 우아한 형태로 찬사 받았습니다.\n\n단순함, 기능성 및 유기적 형태를 특징으로한 중세시대 디자인에 걸맞는 램프가 탄생되었으며, 시대를 초월한 상징적 디자인으로 자리 잡았습니다.\n\n다양한 디자인 전시회, 출판지, 영화 소품 등 종종 등장하였으며, 대중적으로 꾸준히 인기를 끌어왔습니다. 오늘날까지 생산되는 모델로 다양한 색상으로 출시되었습니다.",
  "status": "available",
  "img": "images/products/C5X1B5SOZ-8.jpg",
  "ig": "https://www.instagram.com/p/C5X1B5SOZ-8/",
  "date": "April 5, 2024"
 },
 {
  "id": "C5SoZrsuwDi",
  "cat": "sofa",
  "name": "Cassina Maralunga 2.5 Seater",
  "size": "높이 72 x 가로 190 x 폭 85 cm",
  "desc": "마라룽가 2.5인용이 입고되었습니다.\n\n1973년 비코 마지스트레티가 까시나를 위해 디자인한 마라룽가 모델입니다. 2인용 와이드버전인 2.5인 제품으로\n2인용보다 조금 더 여유있는 시팅감을 주는 제품입니다.",
  "status": "available",
  "img": "images/products/C5SoZrsuwDi.jpg",
  "ig": "https://www.instagram.com/p/C5SoZrsuwDi/",
  "date": "April 3, 2024"
 },
 {
  "id": "C5KymbzubV5",
  "cat": "chair",
  "name": "ARCO BK dinning chair, 1980s",
  "size": "사이즈 문의",
  "desc": "Manufacturer Arco (Netherlands)\nPeriod 1980s\nDimensions 80 x 52 x 42 cm\nCondition Good\n\n80~90년대 출시한 네덜란드 가구회사 ARCO사의 BK다이닝 체어 셋트 입니다. 메탈 소재의 바디 프레임과 합판으로 제작된 이 모델은 포스트 모던 디자인이 반영되었습니다.\n\n오리지널 그레이 컬러 패브릭으로 입고되었으며 총 4점 있습니다.",
  "status": "available",
  "img": "images/products/C5KymbzubV5.jpg",
  "ig": "https://www.instagram.com/p/C5KymbzubV5/",
  "date": "March 30, 2024"
 },
 {
  "id": "C4-O7IXJfLv",
  "cat": "sofa",
  "name": "Maralunga 2 seater",
  "size": "사이즈 문의",
  "desc": "Manufacturer Cassina (Italy)\nPeriod 1970s\nDimensions W158 x D80 x H70cm\nCondition  Signs of Marks &amp; Scratches\n\n1973년 비코 마지스트레티가 까시나를 위해 디자인한 마라룽가 2인 모델입니다.\n\n마라룽가 모델은 수많은 색상과 페브릭 옵션이 존재하며, 현대적이고 화려한 공간부터 전통적이고 차분한 분위기의 공간까지 어울릴 수 있는 디자인으로 소비자들에게 큰 인기를 끌어왔습니다.\n\n해당 제품은 오묘한 컬러감의 청록색 오리지널 가죽으로 입고되었으며, 컬러감을 통하여 공간 속\n포인트를 줄 수 있는 소파입니다.",
  "status": "available",
  "img": "images/products/C4-O7IXJfLv.jpg",
  "ig": "https://www.instagram.com/p/C4-O7IXJfLv/",
  "date": "March 26, 2024"
 },
 {
  "id": "C4pkqmBO1Yi",
  "cat": "sofa",
  "name": "Cleopatra Daybed, 1950s",
  "size": "사이즈 문의",
  "desc": "Manufacturer Auping (Netherlands)\nPeriod 1950s\nDimensions w200cm x d84cm x h58cm\nCondition Scratches and signs of marks\n\n1950년대 딕 코데마이어(Dick Cordemeyer)가 Auping을 위해 디자인한 클레오파트라 데이베드입니다.\n\n와이어 메쉬 베이스와 단단한 금속 프레임으로 구성되어있는 데이베드는 미니멀하고 클래식한 디자인으로, 그 당시 저렴한 가격에 생산이 가능했으며 전 세계적으로 백만 개 이상의 모델을 판매했을만큼 인기가 많았던 모델입니다.\n\n클레오파트라 데이베드는 1982년까지 생산되었으며,\n지금까지 Auping의 가장 성공적인 디자인 중 하나로 남았습니다.",
  "status": "available",
  "img": "images/products/C4pkqmBO1Yi.jpg",
  "ig": "https://www.instagram.com/p/C4pkqmBO1Yi/",
  "date": "March 18, 2024"
 },
 {
  "id": "C39igp_pImq",
  "cat": "sofa",
  "name": "Spectrum BR03 Daybed Sofa",
  "size": "사이즈 문의",
  "desc": "Manufacturer Spectrum (Netherlands)\nPeriod 1960s\nDimensions 69 x 192 x 81 cm\nCondition Upohlostered\n\n1960년대 초반 마틴비서가 스펙트럼을 위해 디자인한 BR03 모델입니다.\n\nBR02 모델의 둥근 튜브 프레임과 달리, BR03 모델은 검은색 사각 메탈 프레임으로 디자인되었습니다.\n\n간단한 동작으로 소파에서 싱글 침대로 바꿔 사용하실 수 있으며,\n심플하고 깔끔한 선이 매력적으로 다가오는 BR 시리즈 모델은 모던하고 미니멀한 공간에 잘 어울리는 제품입니다.\n\n이태리 원단으로 업홀된 제품입니다.",
  "status": "available",
  "img": "images/products/C39igp_pImq.jpg",
  "ig": "https://www.instagram.com/p/C39igp_pImq/",
  "date": "February 29, 2024"
 },
 {
  "id": "C34tEmPJkNr",
  "cat": "cabinet",
  "name": "Danish teak cabinet • Sigvard Bernadotte",
  "size": "사이즈 문의",
  "desc": "",
  "status": "available",
  "img": "images/products/C34tEmPJkNr.jpg",
  "ig": "https://www.instagram.com/p/C34tEmPJkNr/",
  "date": "February 28, 2024"
 },
 {
  "id": "C11IofGpRTg",
  "cat": "sofa",
  "name": "Cassina Maralunga 2.5 Seater",
  "size": "사이즈 문의",
  "desc": "마라룽가 2.5인용이 입고되었습니다.\n\n1973년 비코 마지스트레티가 까시나를 위해 디자인한 마라룽가 모델은 제작년도에 따라 라벨이나 사이즈가 다르게 제작되기도 하는데요,\n그 중 2인용보다 조금 더 큰 2.5인 사이즈 제품이 입고되었습니다.\n\n육안으로 보았을 때 2인 제품과 별 차이가 없지만\n2인용보다 조금 더 여유있는 시팅감을 주는 제품입니다.",
  "status": "available",
  "img": "images/products/C11IofGpRTg.jpg",
  "ig": "https://www.instagram.com/p/C11IofGpRTg/",
  "date": "January 7, 2024"
 },
 {
  "id": "C1EFZR-puHu",
  "cat": "table",
  "name": "Rosenthal Quadrondo Dinning Table, 1980s",
  "size": "사이즈 문의",
  "desc": "VINTAGE SELECT SHOP\n\nOPERATING HOURS\n🏷️월 - 일 1pm -7pm",
  "status": "available",
  "img": "images/products/C1EFZR-puHu.jpg",
  "ig": "https://www.instagram.com/p/C1EFZR-puHu/",
  "date": "December 19, 2023"
 },
 {
  "id": "C08mhvTpnoF",
  "cat": "accessory",
  "name": "Medusa Lamp",
  "size": "사이즈 문의",
  "desc": "Manufacturer Valenti\nDesigner Olaf von Bohr\nPeriod 1960s\nDimensions 65 x 37 x 37 cm\nCondition Good\n\n1968년 Olaf von Bohr가 Valenti를 위해 디자인한 &quot;Medusa&quot;  램프가 입고되었습니다.\n간결하면서도 독특한 디자인이 특징인 메두사 램프는\n기능과 예술을 강조한 램프입니다.\n\n이 램프는 중심 원을 기준으로 알루미늄 판을 조립하여\n제작되었으며, 나선형 패턴의 디자인을 통해 특유의 부드러운\n빛을 만들어 내며 어떤 환경에서든 편안한 분위기를 조성합니다.\n\n메두사 램프는 그리스 신화에 나오는 메두사에 영감을\n받았으며, 밀라노 트리엔날레(Milan Triennale)의\n이탈리안 디자인 영구 컬렉션에 등록되었습니다.\n\n메두사 램프는 단순한 램프 이상으로,\n현대 디자인과 고대 신화를 융합한 예술 작품이며\n현재는 단종되어 소장가치있는 타임피스입니다.",
  "status": "available",
  "img": "images/products/C08mhvTpnoF.jpg",
  "ig": "https://www.instagram.com/p/C08mhvTpnoF/",
  "date": "December 17, 2023"
 },
 {
  "id": "C0qnjwMuoKS",
  "cat": "table",
  "name": "Rosenthal Quadrondo Dinning Table",
  "size": "사이즈 문의",
  "desc": "1980년에 Erwin Nagel이 독일의 Rosenthal을 위해 디자인한 Quadrondo 다이닝 테이블이 입고 되었습니다.\n원형 상판은 네개 피스로 구성되었으며, 모두 펼쳤을 때\n사각 테이블로 변경하여 더 넓게 사용할 수 있는\n기능성 테이블입니다.\n\nRosenthal은 독일 회사로 20세기 초반 고급 식기, 꽃병\n및 기타 장식품에 중점을 두어 당시 고급스러우며\n최신 스타일의 포셀린 식기를 선보였습니다.",
  "status": "available",
  "img": "images/products/C0qnjwMuoKS.jpg",
  "ig": "https://www.instagram.com/p/C0qnjwMuoKS/",
  "date": "December 10, 2023"
 },
 {
  "id": "C0gb2viJ9HI",
  "cat": "table",
  "name": "CADO Chessboard Coffee Table",
  "size": "사이즈 문의",
  "desc": "Manufacturer CADO (Denmark)\nPeriod Mid 20 century\nDimensions W95 x D95 x H42cm\nCondition Good\n\nPoul Cadovius가 덴마크 가구업체 CADO를 위해 디자인한\n체스 보드 커피 테이블입니다.\n\n중세기 덴마크에서 매우 인기 있던 티크 나무로 제작되었으며,\n공간 속 따뜻하고 풍부한 미감을 제공하며 깔끔한 선과 미니멀한 디자인이 특징입니다.\n\n테이블은 우수한 컨디션으로 입고되었으며 그때 당시 제작되었던 오리지널 패키징 박스도 보유 중 입니다.\n\nPoul Cadovius는 20세기 중반에 활동한 현대 디자이너로, 그의 작품은 목재의 자연스러운 아름다움과 조합된 간결한 선들이 돋보이며, 현재도 많은 컬렉터와 대중들에게 인기를 얻고 있습니다.",
  "status": "available",
  "img": "images/products/C0gb2viJ9HI.jpg",
  "ig": "https://www.instagram.com/p/C0gb2viJ9HI/",
  "date": "December 6, 2023"
 },
 {
  "id": "C0Q3UkOO9Fl",
  "cat": "sofa",
  "name": "Cassina Maralunga 2 Seater",
  "size": "사이즈 문의",
  "desc": "1973년 비코 마지스트레티가 까시나를 위해 디자인한 마라룽가\n2인용 모델입니다.\n\n이태리 소가죽으로 업홀하여 새상품급 컨디션으로 판매합니다\n\n마라룽가의 생명인 헤드레스트 메커니즘 작동도 잘되며\n하단 발받침 플라스틱 상태도 우수합니다.",
  "status": "available",
  "img": "images/products/C0Q3UkOO9Fl.jpg",
  "ig": "https://www.instagram.com/p/C0Q3UkOO9Fl/",
  "date": "November 30, 2023"
 },
 {
  "id": "C0Q1rZJusbf",
  "cat": "table",
  "name": "Cassina nesting tables",
  "size": "사이즈 문의",
  "desc": "1970년대 GIANFRANCO FRATTINI가 이탈리아 가구 브랜드 Cassina\n까시나를 위해 디자인한 네스팅 커피테이블 세트입니다.\n\n테이블을 쌓아 보관할 수 있는 구조로 상황에 맞게 사용할 수 있는 실용적인 테이블입니다.\n상판은 오리지널 스모크 글라스와\n바디는 우드로 제작되었습니다.\n\n오리지널 모델은 3개의 테이블이\n한세트로 이루어져 있으며, 해당 제품은 제일 큰 사이즈가 없이 판매되는 상품입니다.",
  "status": "available",
  "img": "images/products/C0Q1rZJusbf.jpg",
  "ig": "https://www.instagram.com/p/C0Q1rZJusbf/",
  "date": "November 30, 2023"
 },
 {
  "id": "C0OOREDOssG",
  "cat": "sofa",
  "name": "TECTA Bauhaus Stripe Sofa",
  "size": "사이즈 문의",
  "desc": "Manufacturer TECTA\nDesigner Walter Gropius\nPeriod 1920s\nDimensions 180 x 75 x h70cm\nCondition Good\n\n독일 건축가이자 바우하우스의 설립자인 Walter Gropius가 1920년대에 TECTA를 위해 디자인한 바우하우스 소파입니다.\n\n오리지널 원단으로 화려한 스트라이프 패턴은 공간 속 포인트를\n주고, 바디 프레임은 표면이 단단하고 갈라짐이나 깨짐이 적은\n애쉬목으로 제작되어 보다 견고합니다.\n\n3인용 사이즈로 패브릭은 세척 및 케어되어 깔끔한 컨디션을\n유지하여 바로 사용 가능합니다.\n\n100년이 지난 디자인으로 현재까지 텍타에서 다양한 원단 재질과 바디 프레임 옵션을 통해 현대화시켜 생산하며 대중들에게 꾸준한 사랑을 받고 있는 디자인입니다.",
  "status": "available",
  "img": "images/products/C0OOREDOssG.jpg",
  "ig": "https://www.instagram.com/p/C0OOREDOssG/",
  "date": "November 28, 2023"
 },
 {
  "id": "C0Ljln4u75K",
  "cat": "chair",
  "name": "Pastoe SP 3005 Dinning Chair",
  "size": "사이즈 문의",
  "desc": "Manufacturer Pastoe (Netherlands)\nPeriod 1972\nDimensions 53 x 54 x h78cm / SH 43cm\nCondition Good\n\n1972년 네덜란드의 가구 업체 파스토(Pastoe)를 위해\n피에르 메넨이 디자인한 SP3005 체어 2점 입고 되었습니다.\n\nPVC와 우드 소재로 제작된 이 모델은 파스토에서 잠시동안\n플라스틱 금형을 활용하여 프레임 제작 실험을 진행했던 시기에 생산되었던 모델입니다.\n\n무광 블랙 바디 프래임과 샌드톤 컬러의 패브릭 조화로 공간 속\n시크한 분위기를 연출합니다.",
  "status": "available",
  "img": "images/products/C0Ljln4u75K.jpg",
  "ig": "https://www.instagram.com/p/C0Ljln4u75K/",
  "date": "November 27, 2023"
 },
 {
  "id": "CyNgz1sum7B",
  "cat": "accessory",
  "name": "MARTINELLI SERPENTE FLOOR LAMP",
  "size": "사이즈 문의",
  "desc": "",
  "status": "available",
  "img": "images/products/CyNgz1sum7B.jpg",
  "ig": "https://www.instagram.com/p/CyNgz1sum7B/",
  "date": "October 10, 2023"
 },
 {
  "id": "CxpWIoMu6Bb",
  "cat": "table",
  "name": "White Italy Round Table",
  "size": "사이즈 문의",
  "desc": "Manufacturer Italy\nDimensions 1200 x (h)750mm\nCondition Good\n\n심플하고 깔끔한 이탈리아 라운드 테이블이 입고되었습니다.\n원형 상판과 세개의 하부 프레임으로 제작된 테이블로\n상판 둘레에 은은하게 보이는 검정 라인이 매력적인 제품입니다.\n다이닝 테이블이나 라운지 테이블 등 다양한 형태로\n사용할 수 있으며 어느 의자에도 매칭하기 좋은 테이블 입니다.",
  "status": "available",
  "img": "images/products/CxpWIoMu6Bb.jpg",
  "ig": "https://www.instagram.com/p/CxpWIoMu6Bb/",
  "date": "September 26, 2023"
 },
 {
  "id": "CxMs4ZnpHFT",
  "cat": "cabinet",
  "name": "Cees Braakman Wood Cabinet",
  "size": "사이즈 문의",
  "desc": "",
  "status": "available",
  "img": "images/products/CxMs4ZnpHFT.jpg",
  "ig": "https://www.instagram.com/p/CxMs4ZnpHFT/",
  "date": "September 14, 2023"
 },
 {
  "id": "CwwnXUYJm2r",
  "cat": "table",
  "name": "Hans Olsen Round Dinning Table",
  "size": "사이즈 문의",
  "desc": "Manufacturer Frem Røjle (Denmark)\nDesigner  Hans Olsen\nPeriod 1960s\nDimensions 76 x 120 x 120 cm\nCondition Good\n\n1960년대 한스 올센 (Hans Olsen)이 디자인하고 덴마크 가구 제조업체 프렘 로이레(Frem Røjle)가 제작한 라운드 다이닝 테이블 세트가 입고되었습니다.\n\n아름다운 질감 패턴을 가진 티크 목재로 제작되어 내구성이 뛰어나고 습기에 강하며, 우드 컬러감은 따듯하고 세련된 분위기를 선사합니다.\n또한 익스텐션 모델로 필요에 따라 상판을 확장시킬 수 있어서 매우 실용적인 테이블 입니다.\n\n한스 올센은 간결하고 기능적인 디자인을 중시하며, 공간이 제한된 환경에서 완벽하게 어울리는 작은 크기와 정교한 디자인을 선호합니다.\n그의 디자인은 혁신적이며 시대를 초월한 매력을 가지고 있어 미드센츄리 가구 컬렉터와 애호가들 사이에서 여전히 큰 인기를 누립니다.",
  "status": "available",
  "img": "images/products/CwwnXUYJm2r.jpg",
  "ig": "https://www.instagram.com/p/CwwnXUYJm2r/",
  "date": "September 3, 2023"
 },
 {
  "id": "CwXGKILO2BY",
  "cat": "cabinet",
  "name": "PASTOE CABINET, 1950s",
  "size": "사이즈 문의",
  "desc": "Manufacturer PASTOE (Netherlands)\nDesigner Cees Braakman\nPeriod 1950s\nDimensions L131cm D43cm  H 119cm\nCondition Good\n\n1950년대 Cees Braakman이 디자인하고 네덜란드 가구 회사 PASTOE에서 제작한 우드 케비넷 입니다.\n바디 부분은 자작나무 제작되었으며 도어는 티크 나무로 제작된 모델 입니다.\n\n캐비넷 안은 충분한 수납 공간으로 이루어져있으며 각 공간 마다 서랍이 있어 실용적인 제품입니다.\n캐비넷 안쪽과 뒷면에 정품 로고가 있으며 깨끗한 컨디션을 유지하고 있습니다.\n\n1848년, D. L.의 아들인 Cees Braakman (1917-1995)은 디자이너 겸 디렉터로서 사장을 맡았고, 1940년대 말에 최초의 파스토 기하학 캐비닛 시리즈를 만든 찰스 &amp; 레이 임스와 알바 알토와 같은 저가의 모듈러 디자인을 옹호하며 회사의 모더니즘 목표를 더욱 발전시켰습니다.\n\n1950년대 동안 이 회사는 소비자가 조립할 수 있는\n캐비닛 시스템을 개발하는 데 집중했으며,\n이는 소비자가 원하는 비스포크 방식의 Made-to-Measure 스토리지 시스템(1955)으로 널리 알렸습니다.",
  "status": "available",
  "img": "images/products/CwXGKILO2BY.jpg",
  "ig": "https://www.instagram.com/p/CwXGKILO2BY/",
  "date": "August 25, 2023"
 },
 {
  "id": "CvwFgI-PBk-",
  "cat": "chair",
  "name": "Castelijn SF Arm Chair, 1980s",
  "size": "사이즈 문의",
  "desc": "Manufacturer  Castelijn (Netherlands)\nPeriod 1980s\nDimensions W 58cm D 56cm H 79cm, Seat Height 47 cm\nCondition Good\n\n1980년대 네덜란드의 카스텔린 (Castelijn)에서 제작한 SF모델 암체어입니다.\n\n카스텔린은 1958년부터 현대적인 가구 디자인을 제작하였으며, 그 시대의 많은 디자인이 오늘날의 클래식 디자인으로 자리 매김한 것으로 알려져 있습니다.\nSF 모델의 경우 현대적인 디자인 요소를 바탕으로 팔걸이와 세련된 검은 튜브 프레임과 같은 기능적 특징으로 의자의 전체적인 미적 감각과 편안 착석감을 제공합니다.\n\n두 점 보유 중이며 검정 색상으로 업홀스토리되어 시크하고 세련된 느낌을 줍니다.",
  "status": "available",
  "img": "images/products/CvwFgI-PBk-.jpg",
  "ig": "https://www.instagram.com/p/CvwFgI-PBk-/",
  "date": "August 9, 2023"
 },
 {
  "id": "CujLf74PNt1",
  "cat": "chair",
  "name": "dsc106 Castelli Fabric Chair",
  "size": "사이즈 문의",
  "desc": "Manufacturer Giancarlo Piretti (Italy)\nPeriod 1960s\nDimensions W 57cm D 75cm H 56cm\nCondition Good",
  "status": "available",
  "img": "images/products/CujLf74PNt1.jpg",
  "ig": "https://www.instagram.com/p/CujLf74PNt1/",
  "date": "July 11, 2023"
 },
 {
  "id": "Ctqmezlv1LL",
  "cat": "accessory",
  "name": "Herda Square Perspex Wall Lamp, 1970s",
  "size": "사이즈 문의",
  "desc": "Manufacturer  Herda Verlichting bv.\nPeriod 1970s\nDimensions W23cm x L23cm\nCondition Edge crack / Overall Good\n\n1970년대 네덜란드 조명회사 Herda Lighting BV가  제작하였습니다.\n벽에 걸어 사용하는 간접 조명 램프로 ‘플렉시글라스’를 통하여 아름다운 그림자 효과를 나타냅니다.\n플렉시 글라스를 4단에 걸쳐 만든 제품으로 밤색 글라스를 통해 나오는 은은한 주황빛이 매력적으로 다가오는\n제품입니다.\n\n플렉시글라스는 고품질 아크릴을 뜻하며 아크릴 소재의 일종으로 더 투명하고 가벼운 특징이 있어\n건축 및 항공유리, 시계 유리, 접착제 등 다양한 분야에서 사용됩니다.\n\nHerda Lighting BV는 네덜란드 암스테르담에 있는 네덜란드 가족 소유의 램프 공장이었습니다.\nHerda는 1946년 설립되어 램프 디자이너로 잘알려진 Willem van Oyen Sr.을 포함하여\n몇몇 최고의 디자이너들을 고용하여 램프를 제작하였습니다.\n\n🏷️ 모서리 부분에 약간의 꺠짐이 있는 것 외에 정상 작동되며 클리닝되어 전체적으로 좋은 컨디션 유지하고 있습니다.",
  "status": "available",
  "img": "images/products/Ctqmezlv1LL.jpg",
  "ig": "https://www.instagram.com/p/Ctqmezlv1LL/",
  "date": "June 19, 2023"
 },
 {
  "id": "CtgNQOuPnOA",
  "cat": "cabinet",
  "name": "Gispen 5600 Modular Storage Unit",
  "size": "사이즈 문의",
  "desc": "Manufacturer Gispen (Netherland)\nDesigner A. R. CORDEMEIJER\nPeriod 1960s\nDimensions H200cm W73cm D36\nCondition Good\n\nAndre Cordeijer가 디자인하고 1962년 네덜란드 가구 회사 Gispen사가 제조한 모듈러 선반입니다. Gispen 5600 모델은 후속 모델이며 진열장, 간이 책상 등 다목적으로 사용 가능하여 사무실, 가정, 상점에서 사용되었습니다.\n\n모듈 시스템을 적용하여 동일 모델에서도 다양한 스타일의 선반이 존재하며, 이 모델은 선반 내부에 전구가 연결되어 간이 책상으로도 활용 가능하며 1단과 2단이 분리되는 케비넷입니다.\n\n그레이 바디에 녹색과 연노랑의 포인트로 매우 이쁜 컬러감을 가지고 있으며 세월의 사용 흔적 외에 상태 또한 매우 양호합니다. 현재는 단종되어 더 이상 생산되지않는 오리지널 제품입니다.\n\n🥑 모듈식으로 분리가 가능한 높은 버전의 제품입니다.\n분리하면 두개의 제품으로도 사용 가능하고 낮은 버전의 캐비넷으로도 사용 가능합니다.",
  "status": "available",
  "img": "images/products/CtgNQOuPnOA.jpg",
  "ig": "https://www.instagram.com/p/CtgNQOuPnOA/",
  "date": "June 15, 2023"
 },
 {
  "id": "CtarahJv83p",
  "cat": "chair",
  "name": "Wink lounge chair, 1980s",
  "size": "사이즈 문의",
  "desc": "Manufacturer Cassina (Italy)\nDesigner Toshiyuki Kita\nPeriod 1980s\nDimensions H100cm L82cm D90cm\nCondition Good\n\n미키 마우스를 연상 시키는 모양으로 미키마우스라고 불리는 윙크 라운지 의자는 기타 도시유키가 디자인하고 1980년대에 카시나가 제조했습니다. 보카시 느낌이 나는 페브릭으로 깨끗하게 업홀스토리 되었습니다.\n\n착석감이나 시팅 포지션이 매우 편안한 라운지 체어이며 디자인적으로도 귀여운 인테리어 포인트 요소가 될 수 있어강추 드리는 제품입니다.",
  "status": "available",
  "img": "images/products/CtarahJv83p.jpg",
  "ig": "https://www.instagram.com/p/CtarahJv83p/",
  "date": "June 12, 2023"
 },
 {
  "id": "CtOF2cNP0W_",
  "cat": "sofa",
  "name": "Maralunga 1 Seater",
  "size": "사이즈 문의",
  "desc": "Manufacturer Cassina (Italy)\nDesigner Vico Magistretti\nPeriod 1970s\nDimensions H100cm W122cm\nCondition Good\n\n꾸준히 사랑받고 있는 카시나 마라룽가 1 씨터 모델이며 업홀되지 않은 네이비 컬러의 오리지널 카시나 가죽입니다.\n\n편안한 착석감과 안락함을 자랑하며 등받이 각도 조절이 가능하여 상황에 맞게 사용할 수 있습니다.",
  "status": "available",
  "img": "images/products/CtOF2cNP0W_.jpg",
  "ig": "https://www.instagram.com/p/CtOF2cNP0W_/",
  "date": "June 7, 2023"
 },
 {
  "id": "Cs-5hLtvTi-",
  "cat": "accessory",
  "name": "ARTEMIDE MEGARON Floor Lamp",
  "size": "사이즈 문의",
  "desc": "Manufacturer Artemide (Italy)\nDesigner Gianfranco Frattini\nPeriod 1970S\nDimensions H182cm W15cm\nCondition Good\n\n1970년대에 제작된 이 모델은 단순하지만 세련미를 돋보이며 위로 퍼져나가는 빛의 반경이 넓어 램프 하나만으로 충분히 어두운 공간을 밝게 비춰줄 수 있는 제품입니다.\n\n디밍스위치로 밝기 조절이 가능하며 할로겐 램프가 장착되어 더 밝고 환한 분위기를 연출 할 수 있습니다.\n\n현재 이 모델은 LED 램프로 출시되며 단종된 컬러의 제품이라 더 소장가치가 있는 매력적인 제품입니다.\n\n디밍 스위치는 부러져있지만 사용하는데 문제는 없으며 전체적으로 상태 양호합니다.",
  "status": "available",
  "img": "images/products/Cs-5hLtvTi-.jpg",
  "ig": "https://www.instagram.com/p/Cs-5hLtvTi-/",
  "date": "June 2, 2023"
 },
 {
  "id": "CsqW69Zvg51",
  "cat": "sofa",
  "name": "Maralunga 3 Seater",
  "size": "사이즈 문의",
  "desc": "Manufacturer Cassina\nDesigner  VICO MAGISTRETTI\nPeriod 1970s\nDimensions 71 x 235 x 85 cm\nCondition Urpholstery (O)\n\n1970년도부터 생산되어 현재까지 꾸준히 사랑받고 있는 마라룽가입니다. 안락하고 편안한 시트감을 주며\n이태리 소가죽 원단으로 업홀되어 풍부한 쿠션감과\n깨끗한 컨디션을 제공 합니다.",
  "status": "available",
  "img": "images/products/CsqW69Zvg51.jpg",
  "ig": "https://www.instagram.com/p/CsqW69Zvg51/",
  "date": "May 25, 2023"
 }
];
